MyPureCloud/terraform-provider-genesyscloud

genesyscloud/resource_genesyscloud_routing_queue_test.go
Queue API now returns an error if a user is assigned to a ring that doesn't exist.
=> Fix error in queue members ring test

genesyscloud/resource_genesyscloud_architect_datatable_row.go, genesyscloud/resource_genesyscloud_architect_datatable_row_test.go
When expanding the plan for genesyscloud_architect_datatable_row.john-smith-2749 to include new values learned so far during apply, provider "registry.terraform.io/mypurecloud/genesyscloud" produced an invalid new value for .properties_json: was cty.StringVal("{"identifier":2749}"), but now cty.StringVal("{"deleted":false,"identifier":2749}").
=> Fix invalid value error when creating new data table and rows with defaults

genesyscloud/resource_genesyscloud_idp_adfs.go, genesyscloud/resource_genesyscloud_idp_generic.go, genesyscloud/resource_genesyscloud_idp_gsuite.go, genesyscloud/resource_genesyscloud_idp_okta.go, genesyscloud/resource_genesyscloud_idp_onelogin.go, genesyscloud/resource_genesyscloud_idp_ping.go, genesyscloud/resource_genesyscloud_idp_salesforce.go
When applying changes to genesyscloud_idp_gsuite.gsuite, provider "provider["registry.terraform.io/mypurecloud/genesyscloud"]" produced an unexpected new value: Root resource was present, but now absent
=> Fix missing resource errors when creating IDP configuration

.github/workflows/test.yml
Tests take longer now with sleeps to avoid eventual consistency issues
=> Upping the timeout for acceptance tests. 

genesyscloud/resource_genesyscloud_user.go
"Other" is a valid phone type, which can also be set via the UI and for integrations such as Teams.
Note: This works fine when creating a new user, however for some reason when updating a user, adding a phone set to other do not take effect (no error is returned, however). This seems like an API bug to me, I'm not sure whether that should block this or not.
=> Add OTHER phone type

genesyscloud/resource_genesyscloud_telephony_providers_edges_phone.go, genesyscloud/resource_genesyscloud_user.go
This crash occurs when a resource field of type map, which has no required attributes, is defined and left empty. E.g. `genesyscloud_user.addresses`
=> [DEVENGAGE-1104] Adding error handling for <nil> to map[string]interface{} type mismatch

genesyscloud/consistency_checker/consistency_checker.go
It affects resources that have had a configuration drift and is unhelpful
=> Removing a check in the consistency checker.

docs/resources/oauth_client.md, genesyscloud/resource_exporter.go, genesyscloud/resource_genesyscloud_outbound_callabletimeset.go
I created this ticket to fix a bug with the callable time sets exporter and realised along the way that go generate should have been ran for [DEVENGAGE-1410](https://inindca.atlassian.net/browse/DEVENGAGE-1410)
=> [DEVENGAGE-1432] Bug fix in callable time sets exporter + oauth_client docs update 

docs/resources/routing_queue.md, examples/resources/genesyscloud_flow/inboundcall_flow_example.yaml, examples/resources/genesyscloud_flow/inboundcall_flow_example2.yaml, examples/resources/genesyscloud_flow/inboundcall_flow_example3.yaml, genesyscloud/resource_genesyscloud_routing_queue.go, genesyscloud/resource_genesyscloud_routing_queue_test.go
I originally was the developer who wrote the skill_groups resource.  However, I did not realize that we needed to add it to the routing_queues object.  While in there I discovered there are three types of "groups" that are supported: groups, teams and skill_groups.  I added support for all three (even though teams does not have a resource yet, so I will add that).
=> Devengage 1451 fix queue groups and skill groups

genesyscloud/resource_genesyscloud_recording_media_retention_policy.go
@diemenschmaschine92 There are a few places where `fmt.Errorf` is used incorrectly. Apologies, I didn't catch it at the time when the PR was up. `fmt.Errorf` is useless unless it's being returned. I figured `log.Fatalf` is better suited in most places. It logs the error and then calls to os.Exit(1). If you think that in some places the program shouldn't exit, and that it should just log the error, comment where and I'll change it to `log.Printf`. Thanks
=> [no-jira] Changing from fmt to log where appropriate

docs/resources/architect_schedules.md, genesyscloud/resource_genesyscloud_architect_schedules.go
I can't figure out why ForceNew was added here.  The put allows you to change the new without any problems.  The problem with schedules is that schedules can be referenced in an Architect flow.  If you change the name and force a new object to be created/delete, it breaks the dependency on architect flow.  I tried to rerun the test, but my OAuth client seems to be missing a permission that I cant figure out;
=> DEVENGAGE-1580: Removed the force new flag off of schedule.

genesyscloud/resource_genesyscloud_knowledge_knowledgebase.go, genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
Because the exporter function was trying to use the pageNumber system when it should have been using cursor logic, it was getting stuck in an infinite loop. Trusting the terraform code generator too much probably caused this one.
It also wasn't exporting both published and unpublished entities.
=> Fixing knowledgebase export process

docs/guides/export.md, templates/guides/export.md.tmpl
I needed to use the exporter tool for the first time today. I was following the example in creating my `export.tf` file and tried to use the `export_as_hcl` attribute. However, I got the following error:
```
│ Error: Unsupported argument
│
│   on export_as_hcl.tf line 12, in resource "genesyscloud_tf_export" "export":
│   12:   export_as_hcl      = true
│
│ An argument named "export_as_hcl" is not expected here.
```
I realized after some looking around that I was using an outdated version of the provider from the example. Upgrading the provider to the latest version resolved this problem.
I'm updating the docs to remove the `required_provider` block from the example because there is no straight-forward way to generate the latest version inside these docs, and instead elected to refer to …
=> Fix: Exporter Docs by removing explicit required_provider and indicate to use the Use Provider dropdown

genesyscloud/resource_genesyscloud_recording_media_retention_policy.go
When the schema for "conditions" has no required fields, it's possible to define an empty object like this inside the resource:
```hcl
conditions{} // type: nil
conditions{ // type: map[string]interface{}
foo = "bar"
}
```
In this case, the `conditions` list will contain a nil item. These checks handle this scenario and prevent the following crash from happening: `panic: interface conversion: interface {} is nil, not map[string]interface {}`
=> Adding !ok checks for type casting

genesyscloud/resource_genesyscloud_outbound_campaign.go, genesyscloud/resource_genesyscloud_outbound_campaign_test.go, genesyscloud/resource_genesyscloud_outbound_campaignrule.go, genesyscloud/resource_genesyscloud_outbound_campaignrule_test.go, genesyscloud/resource_genesyscloud_outbound_sequence_test.go
In conjunction with [this PR](https://github.com/MyPureCloud/terraform-provider-genesyscloud/pull/533) I added functionality and tests to ensure that campaigns, campaign rules, and sequences can be turned off at point of destroy. 
Otherwise, we see the following errors when running destroy:
```
│ Error: Exhausted retries. Last error: [{0 Failed to delete Outbound Campaign: API Error: 400 - Cannot delete a campaign when it is running (f0143ffa-3ba8-4ef2-a1de-17e046f1fe14)  []}]
```
```
│ Error: Exhausted retries. Last error: [{0 Failed to delete Outbound Campaign Rule: API Error: 400 - Cannot delete an enabled campaign rule (ede90978-2d89-4b7c-8ed8-7072415ee8c4)  []}]
```
Since I had also added enable functionality to the outbound sequences resource in the prior PR, I went ahead and added …
=> Campaigns, campaign rules, and sequences can be turned off at point of destroy

docs/resources/telephony_providers_edges_site.md, genesyscloud/resource_genesyscloud_telephony_providers_edges_site.go
Hey guys,
I have added primary_sites and secondary_sites attributes to the site resource.  Please note there were no enhancements to the test because these fields are only applicable when working with physical edges.  I had to borrow a physical edge in test and manually tested the code.  Let me know if you have any questions or concerns
=> DEVENGAGE-1925: Added primary and secondary sites

docs/data-sources/script.md, genesyscloud/data_source_genesyscloud_script.go, genesyscloud/data_source_genesyscloud_script_test.go, genesyscloud/resource_exporter.go
I noticed while working with a recent export project that scripts cannot reference any of the "Default" scripts using the data source.
I checked in with the Genesys Cloud Outbound / Scripting team, and they have intentionally hard-coded the three "Default" scripts to have their own ids that are consistently the same across all orgs. However, they only show up under the "published" listing of scripts.
Instead of having to "know" these IDs, we can update the the data source to allow querying them using the "published" identifier, which is what this PR does.
Here's an example of how I'm using it:
```
data "genesyscloud_script" "Default_Outbound_Script" {
name      = "Default Outbound Script"
published = true
}
resource "genesyscloud_outbound_campaign" "Foo_Campaign" {
script_id             = …
```
=> Allow querying for default scripts in data.genesyscloud_script objects

docs/resources/processautomation_trigger.md, examples/resources/genesyscloud_processautomation_trigger/resource.tf, examples/resources/genesyscloud_processautomation_trigger/trigger_workflow_example.yaml, genesyscloud/process_automation_trigger/data_source_genesyscloud_processautomation_trigger_test.go, genesyscloud/process_automation_trigger/process_automations_triggers_struct.go, genesyscloud/process_automation_trigger/process_automations_triggers_struct_test.go, genesyscloud/process_automation_trigger/resource_genesyscloud_processautomation_trigger.go, genesyscloud/process_automation_trigger/resource_genesyscloud_processautomation_trigger_test.go
I could use some help on this, trying to add the newer functionality for specifying the data format that is sent from triggers to the workflow targets. I think i have most of the ground work laid out, but i still dont seem to be sending the new fields correctly to our rest endpoint. And the provider just hangs when i try to run this, but a trigger is created just without this new configuration.
=> Maes 719 add data format to process automation trigger target

genesyscloud/resource_genesyscloud_knowledge_document_variation.go
The `resource_genesyscloud_knowledge_document_variation` resource was failing on import when the `hyperlink` field was an empty string
=> DEVENGAGE-2080 Document variation hyperlink bug

GNUmakefile, genesyscloud/resource_genesyscloud_integration.go, genesyscloud/util_json.go
Updated the suppressEquivalentJsonDiffs which is used as DiffSuppressFunc for resources that have json string properties.
The method will now ignore any null properties for deep comparison.
=> DEVENGAGE-1948 Fix null properties in jsonencode not being diffsuppressed

GNUmakefile, genesyscloud/external_contacts/resource_genesyscloud_externalcontacts_contact_schema.go, genesyscloud/external_contacts/resource_genesyscloud_externalcontacts_contact_utils.go
Hi, just trying it out if I can fix a recent issue: https://github.com/MyPureCloud/terraform-provider-genesyscloud/issues/611
Problem: The phone number contact can be set just by using display property. The issue is it's auto-formatted after creation/update of the contact to this kind of format: `+1 317-555-7000` regardless of input format.
Solution: Add a DiffSuppressFunc that will compare the phone numbers after E164-formatting them.
=> NO-JIRA: Fix Issue 611

genesyscloud/tfexporter/export_common.go, genesyscloud/tfexporter/genesyscloud_resource_exporter.go, genesyscloud/tfexporter/genesyscloud_resource_exporter_test.go, genesyscloud/tfexporter/hcl_exporter.go, genesyscloud/tfexporter/json_exporter.go, genesyscloud/tfexporter/resource_genesyscloud_tf_export.go, genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
Added `split_files_by_resource` property for resource `genesys_cloud_tf_export`.
Default is `false` and does the current behavior of exporting a giant file. 
If set to `true`, files will be split by resource type eg. genesyscloud_routing_queue.tf(HCL export) / genesyscloud_routing_queue.tf.json (JSON export)
Terraform provider will also be in its own file: provider.tf / provider.tf.json
If there are unresolved attribute, variables will also be declared in separate file: variables.tf / variables.tf.json
Test cases added.
Change on state: Instead of checking for the default export file in the resource read, it will check the entire directory for any files. destroy will also mean deleting every file(and subdirs) inside the export directory.
=> DEVENGAGE-2022 Allow exported resources to be split into multiple files

genesyscloud/resource_genesyscloud_recording_media_retention_policy.go
Fix issue by replacing the API call to use deleteDaysThreshold  = 0 instead of 365.
=> DEVENGAGE-2148 Fix export issue with media retention policies with deleteDaysThreshold <= 365

genesyscloud/resource_genesyscloud_routing_queue.go
Added queue's setting Auto-Answer for digital channels(Email, Message)
media_settings_email {
enable_auto_answer        = true
alerting_timeout_sec      = 60
service_level_duration_ms = 120000
service_level_percentage  = 0.8
}
=> Added queue's setting Auto-Answer for digital channels(Email, Message)

genesyscloud/resource_genesyscloud_routing_queue.go
adding ServiceLevel queue metric to the CGR config
conditional_group_routing_rules {
operator        = "LessThan"
wait_seconds    = 10
condition_value = 80
groups {
member_group_id   = "xxxxxxx"
member_group_type = "SKILLGROUP"
}
metric = "ServiceLevel"
}
=> adding ServiceLevel queue metric to the CGR config

genesyscloud/resource_exporter/resource_exporter.go, genesyscloud/resource_exporter/resource_exporter_test.go
Fixes DEVENGAGE-2166
- Ensure all exported resource names only begin with a letter or underscore.
- Replaces unsafe starting characters with a single underscore. 
- Adds tests for SanitizeResourceName function.
=> DEVENGAGE-2166 Ensure all exported resource names only begin with a letter or underscore

genesyscloud/routing_sms_addresses/resource_genesyscloud_routing_sms_addresses.go
The first time worked on this ticket, I added a check in the getAllSmsAddresses function to see if `Name` was nil before dereferencing the pointer. I forgot to do the same in a log statement in the read function. In the original ticket description, you can see that the stack trace references the getAll function first 
```log
goroutine 302 [running]:
terraform-provider-genesyscloud/genesyscloud.getAllRoutingSmsAddress({0x1e156d9?, 0x28b...
```
When the bug came back around, it referenced the line containing the log statement in the read function:
```log
goroutine 182 [running]:
terraform-provider-genesyscloud/genesyscloud/routing_sms_addresses.readRoutingSmsAddress.func1()
```
=> Removing reference to smsAddress.Name in log statement

genesyscloud/resource_genesyscloud_telephony_providers_edges_phone.go
Fixes DEVENGAGE-2167
- Unlocks result limit in get phones api
=> DEVENGAGE-2167 The genesyscloud_telephony_providers_phone resource can be optimized when exporting more then 10K phones

genesyscloud/resource_exporter/resource_exporter.go, genesyscloud/resource_exporter/resource_exporter_test.go
As I mentioned in the https://inindca.atlassian.net/browse/DEVENGAGE-2189 JIRA, adding a random string of digits as a suffix to _all_ resource names that have been sanitized feels very heavy handed. We certainly need to handle the edge case to prevent a name collision on export, but this should only happen if there is the risk of an actual name collision. 
This PR adds support for detecting such a name collision and using the same approach to add the string of numbers based on the hash of the original name, or otherwise leaving the name alone after being sanitized.
I also added a test case to check for these various cases.
=> [DEVENGAGE-2189] Only add a random suffix on export to resources that have been sanitized with the same matching name pattern

docs/resources/telephony_providers_edges_site.md, genesyscloud/resource_genesyscloud_telephony_providers_edges_site.go, genesyscloud/resource_genesyscloud_telephony_providers_edges_site_test.go
- Getting attribute mismatches when Site with multiple outbound routes are updated. Including just switching around the order of the routes in the list.
- Default Number Plans are not exported (even if they are modified)
- Same attribute mismatch errors on Number Plans when updating number plans on 'update' resource.
- Changed `outbound_routes` type from `schema.TypeList` to `schema.TypeSet`. 
- Also set `outbound_routes` to `schema.SchemaConfigModeAttr` so all outbound routes can be cleared with `outbound_routes = []` 
- Export all number plans including default. Number Plans does not track versions so there's no way to identify which should be exported or can be safely ignored. Reimporting the numebr plans with same names as default causes no problems and overrides as expected.
- Fix …
=> DEVENGAGE-2191 Fix site outbound routes bug(s)

genesyscloud/task_management_workbin/genesyscloud_task_management_workbin_proxy.go
I noticed that the getAll function wasn't using the after cursor in its requests. By setting `pageSize` to 2 and creating 4 workbins, I was able to confirm that it did get stuck in an infinite loop.
=> no jira: Using after cursor in workbins getAll function

examples/resources/genesyscloud_flow/inboundcall_flow_example.yaml, examples/resources/genesyscloud_flow/inboundcall_flow_example2.yaml, examples/resources/genesyscloud_flow/inboundcall_flow_example3.yaml, examples/resources/genesyscloud_flow/inboundcall_flow_example_substitutions.yaml, genesyscloud/resource_genesyscloud_flow_test.go
When you invoke the archy import service, it looks up the flow by name and type. If it exists, it updates the current flow. If not, it creates a new flow. That means if a cx as code user tries to change the name on an update, a new flow with a new guid is created and the previous is not cleaned up. We already noted this in the docs.
The reason why there are so many flows not getting cleaned up is because we were updating the name and type in a few tests and verifying the value after. I changed it so that we update the flow description instead.
=> DEVTOOLING-38: Updating flow description instead of name in tests

genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone_utils.go
The changes made in PR #696 highlighted the fact that a nested function for building an object was being called that tried to look up a phone by ID. This function should only have been invoked on update because then `d.Id()` would have a value. Since these new log comments tried to access the value in phone.Name and phone.Id , they revealed (through a nil pointer error) that nothing was actually being returned from the API call
=> Adding small check to edges_phone build function

.github/workflows/generate.yml, .github/workflows/test.yml, go.mod
A dependabot PR failed because the package update introduced [a function](https://pkg.go.dev/errors#Join) that required go 1.20, which seems like a good sign it's time to upgrade
=> Updating to latest go version 1.21

go.mod
Jenkins build failed with error message: 
```no-highlight
⨯ release failed after 0s                  error=hook failed: go mod tidy: exit status 1; output: go: go.mod file indicates go 1.21, but maximum version supported by tidy is 1.20
```
`go mod tidy` ran fine locally against main, but it did make this small change. So I want to merge this and try again to see if that makes any difference. If not, we may need to go down to 1.20
=> [no jira] go mod tidy

genesyscloud/resource_genesyscloud_routing_settings.go
Looks like the consistency checker isn't able to check the nested field `contactcenter.remove_skills_from_blind_transfer` as it's reading the previous value too quickly right after the update is made. 
Adding a sleep (5s) makes the test pass in the Github matrix test.
=> DEVTOOLING-46 Fix TestAccResourceRoutingSettingsContactCenter test case failing

genesyscloud/architect_grammar/genesyscloud_architect_grammar_init_test.go, genesyscloud/architect_grammar_language/genesyscloud_architect_grammar_language_init_test.go, genesyscloud/authorization_product/authorization_product_resource_init_test.go, genesyscloud/external_contacts/genesyscloud_externalcontacts_contact_init_test.go, genesyscloud/flow_milestone/genesyscloud_flow_milestone_init_test.go, genesyscloud/integration/genesyscloud_integration_init_test.go, genesyscloud/integration_action/genesyscloud_integration_action_init_test.go, genesyscloud/integration_credential/genesyscloud_integration_credential_init_test.go, genesyscloud/integration_custom_auth_action/genesyscloud_integration_custom_auth_action_init_test.go, genesyscloud/outbound/resource_genesyscloud_outbound_init_test.go, genesyscloud/outbound_attempt_limit/outbound_attempt_limit_resource_init_test.go, genesyscloud/outbound_campaign/genesyscloud_outbound_campaign_init_test.go, genesyscloud/outbound_contact_list/outbound_contact_list_resource_init_test.go, genesyscloud/outbound_ruleset/genesyscloud_outbound_ruleset_init_test.go, genesyscloud/outbound_wrapupcode_mappings/genesyscloud_wrapupcode_mappings_init_test.go, genesyscloud/process_automation_trigger/process_automation_trigger_resource_init_test.go, genesyscloud/recording_media_retention_policy/genesyscloud_recording_media_retention_policy_init_test.go, genesyscloud/routing_sms_addresses/genesyscloud_routing_sms_addresses_init_test.go, genesyscloud/station/genesyscloud_station_init_test.go, genesyscloud/task_management_workbin/genesyscloud_task_management_workbin_init_test.go, genesyscloud/team/genesyscloud_team_init_test.go, genesyscloud/telephony/genesyscloud_telephony_init_test.go, genesyscloud/telephony_providers_edges_phone/genesyscloud_telephony_providers_edges_phone_init_test.go, genesyscloud/telephony_providers_edges_site/genesyscloud_telephony_providers_edges_site_init_test.go, genesyscloud/webdeployments_configuration/genesyscloud_webdeployments_configuration_init_test.go, genesyscloud/webdeployments_deployment/genesyscloud_webdeployments_deployment_init_test.go
Going from `reg_instance` -> `regInstance` , and `initTestresources` -> `initTestResources`
=> Renaming funcs and vars in _init_test.go files

genesyscloud/dependent_consumers/genesyscloud_dependent_consumer_proxy.go
`go vet ./genesyscloud/...` returned `genesyscloud/dependent_consumers/genesyscloud_dependent_consumer_proxy.go:61:7: the cancel function returned by context.WithCancel should be called, not discarded, to avoid a context leak` , so this PR is just to correct that
=> No jira: Using cancel function returned from WithCancel

genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
The output of `go vet ./genesyscloud/...` prior to these changes:
```log
genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go:35:2: struct field tag `-` not compatible with reflect.StructTag.Get: bad syntax for struct tag pair
genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go:42:2: struct field tag `-` not compatible with reflect.StructTag.Get: bad syntax for struct tag pair
genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go:47:2: struct field tag `-` not compatible with reflect.StructTag.Get: bad syntax for struct tag pair
```
=> no jira: Satisfying go vet

genesyscloud/architect_ivr/genesyscloud_architect_ivr_proxy.go, genesyscloud/architect_ivr/genesyscloud_architect_ivr_proxy_unit_test.go, genesyscloud/telephony_providers_edges_did_pool/genesyscloud_telephony_providers_edges_did_pool_proxy.go, genesyscloud/util/lists/util_lists.go, genesyscloud/util/lists/util_lists_test.go
This PR addresses 3 issues that existed with the IVR dnis chunking logic:
1. **Speed** - Previously, on update, we were clearing the dnis array on the first PUT, then uploading each chunk again on subsequent requests. So 600 numbers exist in the dnis array, the user adds 20, and we're doing 13 requests (because we're uploading 50 new dnis numbers at a time.) We only need to do one requests in this scenario because the API can handle all 600 dnis that are already associated with the IVR. It's only new numbers that need to be chunked.
* *Solution* - Slice the difference of the dnis array to establish which numbers are new. Set ivr.Dnis to the numbers that already are associated with the ivr (removing the new ones) + the first chunk, and then add on any new chunks incrementally in subsequent …
=> DEVTOOLING-309: Fixing Architect IVR chunking logic 

genesyscloud/resource_genesyscloud_routing_email_route_test.go
This is to fix the test `TestAccResourceRoutingEmailRoute` in the workflow. It was failing with a 400, saying that the email domain already exists. I think going with the uuid package as usual should prevent this. Also the AuthorizeSdk function call was unnecessarily, it turns out
=> No jira: using uuid instead of rand for email route tests

genesyscloud/outbound_campaign/data_source_genesyscloud_outbound_campaign_test.go, genesyscloud/outbound_campaign/genesyscloud_outbound_campaign_init_test.go, genesyscloud/outbound_campaign/genesyscloud_outbound_campaign_proxy.go, genesyscloud/outbound_campaign/resource_genesyscloud_outbound_campaign.go, genesyscloud/outbound_campaign/resource_genesyscloud_outbound_campaign_test.go, genesyscloud/outbound_campaign/resource_genesyscloud_outbound_campaign_utils.go, genesyscloud/outbound_sequence/data_source_genesyscloud_outbound_sequence_test.go, genesyscloud/outbound_sequence/genesyscloud_outbound_sequence_init_test.go, genesyscloud/outbound_sequence/resource_genesyscloud_outbound_sequence_test.go, genesyscloud/station/data_source_genesyscloud_station_test.go, genesyscloud/telephony_providers_edges_phone/data_source_genesyscloud_telephony_providers_edges_phone_test.go, genesyscloud/telephony_providers_edges_phone/genesyscloud_telephony_providers_edges_phone_init_test.go, genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone_test.go, genesyscloud/telephony_providers_edges_site/data_source_genesyscloud_telephony_providers_edges_site_test.go, genesyscloud/telephony_providers_edges_site/genesyscloud_telephony_providers_edges_site_init_test.go, genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_schema.go, genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_test.go, genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_utils.go
This is to fix outbound test failures like:
```log
resource_genesyscloud_outbound_sequence_test.go:41: POST https://login.mypurecloud.com/oauth/token giving up after 1 attempt(s): Post "https://login.mypurecloud.com/oauth/token": net/http: cannot rewind body after connection loss
```
I suspect this is occurring when we try to call the function `AuthorizeSdk` inside the acceptance tests. Instead, this function is being called once from TestMain to save the config to a package-level variable on initialisation of the package, as is already done for the genesyscloud package.
=> No jira: fix outbound tests

docs/resources/routing_utilization.md, examples/resources/genesyscloud_routing_utilization/resource.tf, genesyscloud/data_source_genesyscloud_routing_utilization_label_test.go, genesyscloud/resource_genesyscloud_routing_utilization.go, genesyscloud/resource_genesyscloud_routing_utilization_label_test.go, genesyscloud/resource_genesyscloud_routing_utilization_test.go, genesyscloud/resource_genesyscloud_user.go
This allows configuring label utilization in the Org utilization (routing_utilization resource).
This is one I had spoken to John Carnell about, since it uses a field that's not public yet, so I had to call the api directly instead of using the existing platform-go-sdk call. It's in my to do list to rework that call once the field is public.
One complicated point in this PR involves how OrgUtilization works in the service that owns it. You can have 10 labels in system, configure only 2 of them, for example, and the response will contain all 10 labels (2 with the custom configuration + 8 with default config).
Translating that to terraform would mean that the configured resource has 2 label_utilizations, but the returned resource has 10...It took me a lot of trouble to get that working here …
=> Feat/Adding label support to routing_utilization

genesyscloud/resource_genesyscloud_flow.go
Fixes https://inindca.atlassian.net/browse/DEVTOOLING-353
Now, on export, it outputs like so:
```
resource "genesyscloud_flow" "INQUEUECALL_inqueue" {
file_content_hash = "${filesha256(var.genesyscloud_flow_INQUEUECALL_inqueue_filepath)}"
filepath          = "${var.genesyscloud_flow_INQUEUECALL_inqueue_filepath}"
}
resource "genesyscloud_flow" "INQUEUECALL_Default_In-Queue_Flow" {
file_content_hash = "${filesha256(var.genesyscloud_flow_INQUEUECALL_Default_In-Queue_Flow_filepath)}"
filepath          = "${var.genesyscloud_flow_INQUEUECALL_Default_In-Queue_Flow_filepath}"
}
resource "genesyscloud_flow" "VOICEMAIL_Default_Voicemail_Flow" {
file_content_hash = "${filesha256(var.genesyscloud_flow_VOICEMAIL_Default_Voicemail_Flow_filepath)}"
filepath          = …
```
=> [DEVTOOLING-353] Include the flow type in the resource name export

genesyscloud/webdeployments_configuration/resource_genesyscloud_webdeployments_configuration_schema.go
Don't export the `authentication_settings` block in the web config resource if an `integration_id` field is missing
=> DEVTOOLING-424 Fix

genesyscloud/resource_genesyscloud_init_test.go
Schedule groups are used in the journey action map tests, so this resource needed to be added back to the provider for the genesyscloud package tests. This didn't cause any cyclic issues thanks to the big refactoring done recently @carnellj-genesys 🙌
=> Adding schedule groups back to genesyscloud test provider

.goreleaser.yml
The error produced by the jenkins release job:
```
• setting defaults
• running before hooks
• running                                        hook=go mod tidy
⨯ release failed after 0s                  error=hook failed: shell: 'go mod tidy': exit status 1: go: errors parsing go.mod:
/var/build/workspace/build-platform-cxascode/go.mod:5: unknown directive: toolchain
```
If this doesn't fix the jenkins build, we'll have to revert a recent dependabot PR that introduced this "toolchain" line
=> no-jira: Commenting out goreleaser temporarily to run jenkins build

.github/workflows/generate.yml, .github/workflows/test-workflow.yml, .github/workflows/test.yml, go.mod
We had an issue with the release in which goreleaser said it did not recognise `toolchain` in the go.mod file. I suspect this is because goreleaser runs on a version of go older than 1.21; when toolchain was introduced. I tried to configure goreleaser to use a specific go version but as far as I'm aware, that's not possible.
I tried going back to 1.20, but there was some dependency in the project that was forcing the Go version to update to 1.21 and add the toolchain line, and I couldn't figure out which dependency it was or how to stop the automatic go version upgrade (it would happen anytime any `go` command was run e.g. `go mod tidy`). 
In the end, updating the go version the other way, up to 1.22, fixed the problem and the toolchain line isn't automatically being added anymore. …
=> No jira: Go 1.22

genesyscloud/resource_genesyscloud_user.go
Remove really low timeout configuration for genesyscloud_user resource. It causes context deadline exceeded errors.
Introduced here: https://github.com/MyPureCloud/terraform-provider-genesyscloud/pull/809/files#diff-7ed088e59ad27d5e4856608e5c008a2bf9fe469e5e54fb3ca534f2623c32d0f6R209
=> Fix DEVTOOLING-472

.gitignore, docs/resources/routing_email_route.md, genesyscloud/resource_exporter/resource_exporter.go, genesyscloud/resource_exporter/resource_exporter_custom.go, genesyscloud/resource_exporter/resource_exporter_custom_test.go, genesyscloud/routing_email_route/genesyscloud_routing_email_route_init_test.go, genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route.go, genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route_schema.go, genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route_test.go, genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route_utils.go, genesyscloud/tfexporter/genesyscloud_resource_exporter.go
Fixes DEVTOOLING-497 self-referential reply_email_address.route_id gets exported in the genesyscloud_routing_email_route resource. 
Also adds:
- Mutual exclusivity to reply_email_address block and the from_email and auto_bcc fields as per the API and UI behaviors.
- Mutual exclusivity to flow_id and queue_id fields as per the API and UI behaviors
- Tests for verifying configuration errors when these fields are used together
- Logic for determining when to add reply_email_address during create/update
- Syntax tweaks/fixes to various lines of code along the way as per VS Code editor recommendations
=> Fixes DEVTOOLING-497 self-referential reply_email_address.route_id

genesyscloud/data_source_genesyscloud_routing_email_domain_test.go, genesyscloud/recording_media_retention_policy/resource_genesyscloud_recording_media_retention_policy_test.go, genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route_test.go
For now, I'm not going to worry about why this method is duplicated three times. I just noticed that pageNum and pageSize were in the wrong order, and thats why domains were not getting cleaned up. I also added a bit more logging
=> no-jira: Fixing routing email domain cleanup function 

genesyscloud/architect_flow/data_source_genesyscloud_flow.go
The way this code was written could cause an infinite loop to occur. The for loop was unnecessary since the proxy function handles the pagination logic and returns all the flows. If more than zero flows was returned without error, and none of them matched `d.Get("name")` , then nothing would break the for loop
=> No jira: flow data source read

genesyscloud/group_roles/resource_genesyscloud_group_roles_schema.go, genesyscloud/oauth_client/resource_genesyscloud_oauth_client_proxy.go, genesyscloud/oauth_client/resource_genesyscloude_oauth_client_unit_test.go, genesyscloud/orgauthorization_pairing/genesyscloud_orgauthorization_pairing_proxy.go, genesyscloud/orgauthorization_pairing/resource_genesyscloud_orgauthorization_pairing.go, genesyscloud/responsemanagement_responseasset/genesyscloud_responsemanagement_responseasset_proxy.go, genesyscloud/routing_queue/resource_genesyscloud_routing_queue_schema.go, genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
@carnellj-genesys @HemanthDogiparthi12 @dginty4 @BrianMoyles An update on why we didn't merge into main yesterday evening:
There were merge conflicts going from dev -> main , so we checked out a new branch off dev; `dev-v2` , merged `main` into `dev-v2` and fixed all the merge conflicts there. This PR is to merge dev-v2 back into dev. Hopefully then there will be no merge conflicts. 
My theory as to how these merge conflicts came about is that some branch since the last release was accidentally checked off of main. Not sure what else could have caused this at the moment.
=> no jira: Fixing merge conflicts on dev branch 

genesyscloud/outbound/resource_genesyscloud_outbound_messagingcampaign.go
Set `message_column` to optional and modified description.
Added verification logic into add and update functions.
Unfortunately it's not possible to use `ExactlyOneOf` or `ConflictsWith` in the schema as `sms_config` is a `TypeSet`. Changing `TypeSet` to `TypeList` requires more changes to most functions.
=> Fix for issue 993 : Changed message_column to optional and add verification logic

docs/resources/outbound_messagingcampaign.md, genesyscloud/resource_genesyscloud_quality_forms_evaluation.go
This PR Fixes the exporting of the 'published' attribute by using the `GetQualityFormsEvaluationsBulkContexts` api call, which returns a list of published versions of an evaluation form. This can be used to determine if published should be set to true / false
=> bug/devtooling 362 - Evaluation forms incorrectly assigning published attribute

genesyscloud/resource_genesyscloud_journey_segment.go
This PR changes the build function calls for 2 attributes, which caused the test to fail with the error:
`panic: reflect.Set: value of type *platformclientv2.Requestcontext is not assignable to type *platformclientv2.Patchcontext`
=> bug/DEVTOOLING-557 - Changed Build Function Call to fix type difference

genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route.go, genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route_test.go, genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route_utils.go
This PR calls the cleanup function in routing email routes to prevent maximum resources exceeded error, and also makes linter changes
=> Bug/devtooling 597 - Routing email route test failing 

genesyscloud/webdeployments_configuration/data_source_genesyscloud_webdeployments_configuration.go, genesyscloud/webdeployments_configuration/data_source_genesyscloud_webdeployments_configuration_test.go, genesyscloud/webdeployments_configuration/resource_genesyscloud_webdeployments_configuration.go, genesyscloud/webdeployments_configuration/resource_genesyscloud_webdeployments_configuration_test.go, genesyscloud/webdeployments_configuration/utils/resource_genesyscloud_webdeployments_configuration_utils.go, genesyscloud/webdeployments_deployment/data_source_genesyscloud_webdeployments_deployment_test.go, genesyscloud/webdeployments_deployment/resource_genesyscloud_webdeployments_deployment.go, genesyscloud/webdeployments_deployment/resource_genesyscloud_webdeployments_deployment_test.go
This PR adds a cleanup function to the tests for webdeployments resources to prevent exceeding maximum number of resources.
This PR also includes changes to the resources from the linter
=> bug/DEVTOOLING-436 - Added cleanup function for webdeployments resources

genesyscloud/routing_queue/resource_genesyscloud_routing_queue.go
Before we added the BYPASS_CONSISTENCY_CHECKER capabilities, this error was needed to prevent users from getting blocked. Now this message can be logged.
=> DEVTOOLING-449: Logging error in queue create/update instead of failing

.goreleaser.yml
During our release process, we download the latest version of goreleaser. On the last release attempt it downloaded v2.0.1 (probably for the first time ever) and now the build is failing because the goreleaser config file does not specify version 2
The error 
```
Downloading GoReleaser v2.0.1...
• starting release...
• only configurations files on  version: 2  are supported, yours is  version: 0 , please update your configuration
```
=> Specifying version 2 in the goreleaser file to fix build

docs/resources/widget_deployment.md, examples/resources/genesyscloud_widget_deployment/resource.tf, genesyscloud/architect_ivr/resource_genesyscloud_architect_ivr_schema.go, genesyscloud/data_source_genesyscloud_widget_deployment_test.go, genesyscloud/external_contacts/resource_genesyscloud_externalcontacts_contact_schema.go, genesyscloud/outbound_callabletimeset/resource_genesyscloud_outbound_callabletimeset_schema.go, genesyscloud/outbound_dnclist/resource_genesyscloud_outbound_dnclist_schema.go, genesyscloud/outbound_settings/resource_genesyscloud_outbound_settings_schema.go, genesyscloud/resource_genesyscloud_widget_deployment.go, genesyscloud/resource_genesyscloud_widget_deployment_test.go, genesyscloud/routing_sms_addresses/genesyscloud_routing_sms_addresses_schema.go, genesyscloud/scripts/resource_scripts_schema.go, genesyscloud/task_management_workitem/resource_genesyscloud_task_management_workitem_schema.go, genesyscloud/task_management_worktype/resource_genesyscloud_task_management_worktype_schema.go, genesyscloud/telephony_providers_edges_did/genesyscloud_telephony_providers_edges_did_schema.go, genesyscloud/telephony_providers_edges_did_pool/resource_genesyscloud_telephony_providers_edges_did_pool_schema.go, genesyscloud/telephony_providers_edges_extension_pool/genesyscloud_telephony_providers_edges_extension_pool_schema.go, genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone_schema.go, genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_schema.go, genesyscloud/tfexporter/resource_genesyscloud_tf_export.go, genesyscloud/util/resourcedata/resourcedata.go, genesyscloud/validators/validators.go, genesyscloud/webdeployments_configuration/resource_genesyscloud_webdeployments_configuration_schema.go
API change is described here - [https://developer.genesys.cloud/forum/t/deprecation-removal-acd-chat-v1-0/25174](https://developer.genesys.cloud/forum/t/deprecation-removal-acd-chat-v1-0/25174)
I also added support for the two other client types - v2 and third-party
=> Devtooling 501: Removing support for v1 and v1-http widget deployments

genesyscloud/tfexporter/export_common.go, genesyscloud/tfexporter/genesyscloud_resource_exporter.go, genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
Adds support for using sanitized names in export. This allows you to copy the names from the results of an export and reuse them as include/exclude filters in a new export
For example, I was able to run an export of a fresh/clean org and export the resources that were already prebuilt. This allows me to then construct an `exclude_filter_resources` to export all non-default resources created:
```
exclude_filter_resources = [
"genesyscloud_routing_utilization::routing_utilization",
"genesyscloud_flow::INQUEUECALL_Default_In-Queue_Flow",
"genesyscloud_flow::VOICEMAIL_Default_Voicemail_Flow",
"genesyscloud_routing_settings::routing_settings",
"genesyscloud_telephony_providers_edges_site::PureCloud_Voice_-_AWS",
"genesyscloud_outbound_callanalysisresponseset::Default_Response_Set", …
```
=> DEVTOOLING-643 : Adds support for using sanitized names in export.

genesyscloud/telephony/resource_genesyscloud_telephony_providers_edges_trunkbasesettings.go
PR #1109 caused the unit test `TestForExportCycles` to fail because of a potential cyclic relationship between exported resources. This PR is just commenting out that RefAttr and fixing the unit tests before the release next Tuesday. 
DEVTOOLING-676 has been created to properly investigate the issue in the next sprint.
=> No jira: fix export unit test

docs/resources/routing_utilization.md, docs/resources/routing_utilization_label.md, genesyscloud/resource_genesyscloud_user.go, genesyscloud/resource_genesyscloud_user_test.go, genesyscloud/routing_utilization/resource_genesyscloud_routing_utilization_schema.go, genesyscloud/routing_utilization/resource_genesyscloud_routing_utilization_test.go, genesyscloud/routing_utilization_label/data_source_genesyscloud_routing_utilization_label_test.go, genesyscloud/routing_utilization_label/resource_genesyscloud_routing_utilization_label_schema.go, genesyscloud/routing_utilization_label/resource_genesyscloud_routing_utilization_label_test.go, genesyscloud/routing_utilization_label/resource_genesyscloud_routing_utilization_label_utils.go
Utilization Labels are now GA, so I'm removing the mentions of it not being available and checks from tests, since they're not needed anymore.
=> Cleanup/Remove utilization label availability check / mentions

genesyscloud/tfexporter/genesyscloud_resource_exporter.go
Fixes DEVTOOLING-674 by allowing the sanitizeMap function to continue processing as sanitizeE164Number and sanitizeRrule functions could return empty strings. If they do, we want to filter them out (further down the sanitizeMap function) unless they are explicitly marked to be kept by the AllowForZeroValues config to be retained as blank / zero values.
Presumably, when these functions were originally written, they were likely copied from the above if statements that explicitly continue (for good reason).
=> Fixes DEVTOOLING-674

GNUmakefile, README.md
Add a `make` command for generating docs (for consistency, as I was using `make build` and `make test`, etc and found it frustrating that there wasn't one for docs).
=> Add `make` command for generating docs

genesyscloud/data_source_genesyscloud_knowledge_knowledgebase.go, genesyscloud/resource_genesyscloud_knowledge_knowledgebase.go, genesyscloud/resource_genesyscloud_knowledge_v1_category.go, genesyscloud/resource_genesyscloud_knowledge_v1_document.go, genesyscloud/validators/validators.go
Inspired by https://inindca.atlassian.net/browse/DEVTOOLING-632 and in addition to https://github.com/MyPureCloud/terraform-provider-genesyscloud/pull/1127 , this pulls in the latest language codes the API schema supports for Knowledge / Knowledge Base / Categories / Docs. 
See values available in dropdown for language field in API Explorer:
- https://apicentral.genesys.cloud/api-explorer\#post-api-v2-knowledge-knowledgebases 
- https://apicentral.genesys.cloud/api-explorer\#post-api-v2-knowledge-knowledgebases--knowledgeBaseId--languages--languageCode--categories
=> Update latest language codes

genesyscloud/team/genesyscloud_team_proxy.go
https://inindca.atlassian.net/browse/DEVTOOLING-607 - Export did not finish and was stuck on the getAll call on the teams resource. This was due to the re-initialization of the after variable in the proxy call, causing the API to only ever return the first page of data and causing the export to hang.
=> Bug/DEVTOOLING-607: Fixed export for teams resource not finishing

genesyscloud/routing_queue_outbound_email_address/resource_genesyscloud_routing_queue_outbound_email_address.go, genesyscloud/routing_queue_outbound_email_address/resource_genesyscloud_routing_queue_outbound_email_address_schema.go, genesyscloud/routing_queue_outbound_email_address/resource_genesyscloud_routing_queue_outbound_email_address_utils.go, genesyscloud/routing_queue_outbound_email_address/resource_genesyscloud_routing_queue_outbound_email_address_utils_unit_test.go
This bug occurs because there are routing queues with empty objects (`outboundEmailAddress: {}`). We need to filter those queues out when exporting the `genesyscloud_routing_queue_outbound_email_address` resource
=> Fix DEVTOOLING-703

genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route.go, genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route_utils.go
When migrating to independent outbound routes resource, the error 
`OutboundRoute with name 'Default Outbound Route' already exists` can occur
This PR checks the existing routes within a site and only creates any new sites, to prevent the error.
This allows users to migrate existing routes, create new routes, or do both at the same time
=> Bug/Devtooling-677: Error Migrating routes to independent resource

docs/resources/journey_action_map.md, docs/resources/journey_outcome.md, docs/resources/journey_segment.md, genesyscloud/resource_genesyscloud_journey_action_map.go, genesyscloud/resource_genesyscloud_journey_segment.go
When configuring Journey resources like segments, outcomes or action maps, it is now possible to use App stream type. Also, the documentation around supported session types was updated, to specify the allowed values.
=> feat/GPE-14463 add support for App stream type on Journey resources

docs/data-sources/telephony_providers_edges_site.md, genesyscloud/resource_exporter/resource_exporter.go, genesyscloud/telephony_providers_edges_site/data_source_genesyscloud_telephony_providers_edges_site.go, genesyscloud/telephony_providers_edges_site/data_source_genesyscloud_telephony_providers_edges_site_test.go, genesyscloud/telephony_providers_edges_site/genesyscloud_telephony_providers_edges_site_proxy.go, genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site.go, genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_schema.go, genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_test.go, genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_utils.go, genesyscloud/tfexporter/datasource_export_config.go, genesyscloud/tfexporter/genesyscloud_resource_exporter.go, genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go, genesyscloud/tfexporter/tf_exporter_resource_test.go
Due to https://inindca.atlassian.net/browse/DEVTOOLING-606, this PR:
Removes managed attribute from sites data source
Automatically sets managed sites to data on export
Searches both managed and unmanaged sites on getSiteByName function call
Due to import cycles, the genesyscloud_resource_exporter will read the DataSourceManagedSites on export to determine which resources should be exported as data
=> Bug/devtooling-606 Export Managed sites as data sources 

.github/workflows/go-checks.yml, genesyscloud/architect_ivr/data_source_genesyscloud_architect_ivr.go
Even though we'll be disabling the acceptance tests on GitHub soon, I think it would be a good idea to keep a workflow that checks the following:
1. `go generate` doesn't change any files
2. `go mod tidy` doesn't change any files
3. `go vet ./genesyscloud/...` doesn't produce any output 
I renamed the "Generate" job to "Go Checks" and added all the steps outlined above. Eventually, we can add the linter as well.
=> No jira: go checks

docs/resources/quality_forms_survey.md, genesyscloud/resource_genesyscloud_quality_forms_survey.go
DEVTOOLING-625 (adding ID fields to the forms_evaluation resource) broke the export tests. They started failing because of a problem with the forms_survey exporter. forms_evaluation and forms_survey both have `question_groups`, so they shares some plumbing. I added the IDs to the forms_survey resource to fix the problem.
=> Devtooling 625: fix export test

docs/data-sources/telephony_providers_edges_did.md, genesyscloud/architect_ivr/resource_genesyscloud_architect_ivr.go, genesyscloud/external_contacts/resource_genesyscloud_externalcontacts_contact_utils.go, genesyscloud/group/resource_genesyscloud_group_utils.go, genesyscloud/provider/provider.go, genesyscloud/provider/provider_utils.go, genesyscloud/resource_genesyscloud_location.go, genesyscloud/resource_genesyscloud_user.go, genesyscloud/telephony_providers_edges_did/genesyscloud_telephony_providers_edges_did_proxy.go, genesyscloud/telephony_providers_edges_did/genesyscloud_telephony_providers_edges_did_schema.go, genesyscloud/telephony_providers_edges_did_pool/genesyscloud_telephony_providers_edges_did_pool_proxy.go, genesyscloud/telephony_providers_edges_did_pool/resource_genesyscloud_telephony_providers_edges_did_pool.go, genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone_utils.go, genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site.go, genesyscloud/util/lists/util_lists.go, genesyscloud/util/util_e164.go, genesyscloud/util/util_e164_test.go, genesyscloud/validators/validators.go
Hardening E.164 handling that may occur by ensuring all instances that we validate for an E.164 formatted number from user config (which are applied on create/update) are also returned (via read) as an E.164 formatted number to maintain consistency in number handling. This likely means we could remove the custom validate export handling for E164 that was inconsistently applied and used custom logic.
=> Inspired by DEVTOOLING-741 - Hardening E.164 handling

genesyscloud/user/genesyscloud_user_proxy.go
This fixes an oversight during #1192 where retrieving all users before adding them to the cache wasn't retrieving the expanded form of users.
=> Fix DEVTOOLING-780

genesyscloud/outbound_callanalysisresponseset/resource_genesyscloud_outbound_callanalysisresponseset_schema.go
Adds extra Export RefAttrs that could exist and reference flows on genesyscloud_outbound_callanalysisresponseset.
Found this while reviewing export outputs from Japan orgs.
=> NO-JIRA: Adds extra Export RefAttrs on genesyscloud_outbound_callanalysisresponseset

genesyscloud/idp_adfs/resource_genesyscloud_idp_adfs.go, genesyscloud/idp_generic/resource_genesyscloud_idp_generic.go, genesyscloud/idp_gsuite/resource_genesyscloud_idp_gsuite.go, genesyscloud/idp_okta/resource_genesyscloud_idp_okta.go, genesyscloud/idp_onelogin/resource_genesyscloud_idp_onelogin.go, genesyscloud/idp_ping/resource_genesyscloud_idp_ping.go, genesyscloud/idp_salesforce/resource_genesyscloud_idp_salesforce.go, genesyscloud/organization_authentication_settings/genesyscloud_organization_authentication_settings_proxy.go, genesyscloud/organization_authentication_settings/resource_genesyscloud_organization_authentication_settings.go, genesyscloud/organization_authentication_settings/resource_genesyscloud_organization_authentication_settings_unit_test.go, genesyscloud/outbound_settings/genesyscloud_outbound_settings_proxy.go, genesyscloud/outbound_settings/resource_genesyscloud_outbound_settings.go, genesyscloud/outbound_wrapupcode_mappings/resource_genesyscloud_outbound_wrapupcodemappings.go, genesyscloud/routing_settings/resource_genesyscloud_routing_settings.go, genesyscloud/routing_utilization/resource_genesyscloud_routing_utilization.go
This PR fixes DEVTOOLING-786 and DEVTOOLING-740 by improving permission handling for single-instance resources
Background:
- Many single-instance resources (e.g., `genesyscloud_outbound_settings`) return a simple `ResourceMeta` object in their `getAll...()` function.
- These resources have API access permissions associated with them.
- The exporter checks for permission errors after the initial `getAll...()` call and handles them via logging if `log_permissions_errors` is configured.
- Constructing a simple `ResourceMeta` object bypasses this check, causing errors in the downstream `read` functions even when `log_permissions_errors` is set.
Fix:
- Update the `getAll...()` function for single-instance resources that return key-value objects.
- Implement an API call to confirm user …
=> Fixes DEVTOOLING-786 and DEVTOOLING-740 as well as other resources that could be impacted

genesyscloud/responsemanagement_responseasset/resource_genesyscloud_responsemanagement_responseasset.go, genesyscloud/responsemanagement_responseasset/resource_genesyscloud_responsemanagement_responseasset_schema.go
Removes the hard coded `division_id` on `responsemanagement_responseasset` export
=> Devtooling-819: not hard-coded division_id 

docs/resources/oauth_client.md, genesyscloud/oauth_client/resource_genesyscloud_oauth_client_schema.go
Update `oauth_client`'s `authorized_grant_type` attribute to accept both `SAML2BEARER` and `SAML2-BEARER` values (the API allows both versions, but outputs as SAML2-BEARER in the API and export. It's important that the export be able to be reapplied right away, so this fix handles that).
Otherwise, this can happen when trying to apply an export of the oauth_client resource:
```
│ Error: expected authorized_grant_type to be one of ["CODE" "TOKEN" "SAML2BEARER" "PASSWORD" "CLIENT-CREDENTIALS"], got SAML2-BEARER
│
│   with genesyscloud_oauth_client.TT_SAML,
│   on genesyscloud.tf line 2799, in resource "genesyscloud_oauth_client" "TT_SAML":
│ 2799:   authorized_grant_type         = "SAML2-BEARER"
│
╵
```
=> NOJIRA fix oauth client.authorized_grant_type to accept SAML2-BEARER value

genesyscloud/tfexporter/genesyscloud_resource_exporter.go
NOJIRA - Fixes an issue where some data resources return more than just the name, and these can have dynamic references. The biggest offender of this is the genesyscloud_telephony_providers_edges_site_outbound_route data resource, which can have multiple routes named Default with different site ids
```
data "genesyscloud_telephony_providers_edges_site_outbound_route" "Default_Outbound_Route_1394897235" {
name    = "Default Outbound Route"
site_id = "6cd953fd-7040-4963-8f50-b4ebd866027a"
}
```
becomes
```
data "genesyscloud_telephony_providers_edges_site_outbound_route" "Default_Outbound_Route_1394897235" {
name    = "Default Outbound Route"
site_id = "${genesyscloud_telephony_providers_edges_site.Phone.id}"
}
```
=> NOJIRA - Fix data resource not outputting dynamic references

genesyscloud/outbound_contact_list/data_source_genesyscloud_outbound_contact_list.go, genesyscloud/outbound_contact_list/genesyscloud_outbound_contact_list_proxy.go, genesyscloud/outbound_contact_list/resource_genesyscloud_outbound_contact_list.go, genesyscloud/outbound_contact_list/resource_genesyscloud_outbound_contact_list_utils.go, genesyscloud/outbound_contact_list_contact/genesyscloud_outbound_contact_list_contact_proxy.go, genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact.go
This is done by:
* Implementing caching in the contact_lists package 
* Removing the singleton pattern in the proxies of both packages (this may not increase export speed but it will for read/plan operations)
* Increasing pageSize from 50 to 100 when paginating through contacts 
(The issue described in the ticket DEVTOOLING-750 was mostly fixed in [PR 1136](https://github.com/MyPureCloud/terraform-provider-genesyscloud/pull/1336). These changes only improved the export time marginally)
=> DEVTOOLING-750: Improving export speed for contact_lists and contact_lists_contacts resources

genesyscloud/architect_user_prompt/genesyscloud_architect_user_prompt_proxy.go, genesyscloud/architect_user_prompt/resource_genesyscloud_architect_user_prompt.go, genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
This PR changes the functionality of the getAllPrompts due to hitting the 10,000 limit.
To prevent this, the API will be called with different name filters based on starting letter of the prompt
=> [DEVTOOLING-849] API Limitation on Prompt Export

genesyscloud/journey_action_template/resource_genesyscloud_journey_action_template_schema.go, main.go
During the refactoring of journey_action_template resource into its own package (PR #1408), we forgot to SetRegistrar inside main.go, so the resource, datasource and exporter would not have been included in the next version
=> No jira: Adding journey action template to provider 

genesyscloud/outbound_attempt_limit/data_source_genesyscloud_outbound_attempt_limit.go, genesyscloud/outbound_attempt_limit/data_source_genesyscloud_outbound_attempt_limit_test.go, genesyscloud/outbound_attempt_limit/outbound_attempt_limit_resource_init.go, genesyscloud/outbound_attempt_limit/resource_genesyscloud_outbound_attempt_limit.go, genesyscloud/outbound_attempt_limit/resource_genesyscloud_outbound_attempt_limit_test.go
```
data_source_genesyscloud_outbound_attempt_limit_test.go:19: Step 1/1 error: Error running pre-apply refresh: exit status 1
Error: Invalid resource type
on terraform_plugin_test.tf line 2, in resource "genesyscloud_outbound_attempt_limit" "attempt_limit":
2: resource "genesyscloud_outbound_attempt_limit" "attempt_limit" {
The provider hashicorp/genesyscloud does not support resource type
"genesyscloud_outbound_attempt_limit". Did you mean
"genesyscloud_outbound_attemptlimit"?
--- FAIL: TestAccDataSourceOutboundAttemptLimit (0.20s)
```
=> No jira: fix attempt limit test

genesyscloud/telephony_providers_edges_site_outbound_route/data_source_genesyscloud_telephony_providers_edges_site_outbound_route.go, genesyscloud/telephony_providers_edges_site_outbound_route/data_source_genesyscloud_telephony_providers_edges_site_outbound_route_test.go, genesyscloud/telephony_providers_edges_site_outbound_route/genesyscloud_telephony_providers_edges_site_outbound_route_proxy.go, genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route.go, genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route_test.go, genesyscloud/util/testrunner/testrunner.go
Fix default outbound routes by enabling updating the default outbound route during terraform create
=> Fix DEVTOOLING-936 - Allow updates to default outbound routes

genesyscloud/user/resource_genesyscloud_user_utils.go
When the users resource was refactored to the package structure in v1.45.0 , we stopped returning this APIResponse object when the patch operation fails. This means that the *retry when version is mismatch* logic that the operation is wrapped in cannot work. 
The restore deleted user logic after 1.45.0: https://github.com/MyPureCloud/terraform-provider-genesyscloud/blob/v1.45.0/genesyscloud/user/resource_genesyscloud_user_utils.go
And before (1.44.0): https://github.com/MyPureCloud/terraform-provider-genesyscloud/blob/v1.44.0/genesyscloud/resource_genesyscloud_user.go#L721
=> returning response so IsVersionMismatch function can work

docs/resources/architect_schedules.md, genesyscloud/architect_schedules/data_source_genesyscloud_architect_schedules_test.go, genesyscloud/architect_schedules/resource_genesyscloud_architect_schedules.go, genesyscloud/architect_schedules/resource_genesyscloud_architect_schedules_schema.go, genesyscloud/architect_schedules/resource_genesyscloud_architect_schedules_test.go, genesyscloud/architect_schedules/resource_genesyscloud_architect_schedules_unit_test.go, genesyscloud/architect_schedules/resource_genesyscloud_architect_schedules_utils.go, genesyscloud/journey_action_map/resource_genesyscloud_journey_action_map_utils.go, genesyscloud/tfexporter/tf_exporter_resource_test.go
If an architect schedule defines its recurrence rule (`rrule`) as `"FREQ=WEEKLY;INTERVAL=1;BYDAY=MO,TU,WE"` , then the start date must be a Monday, Tuesday or Wednesday. If it is not, the API will automatically push the day back until it matches the rrule (in this case it will transform to the next Monday)  
This PR adds a check to the create and update context to establish the days specified in the rrule (if any), and then establish which day of the week the start date is. If the start date day is not in the rrule, fail. 
@carnellj-genesys After exporting all schedules in an org and applying them against another org, I found that there were schedules that did not conform to the rules (i.e. had start dates that were not in the rrule), so the deployment failed. I don't think this is an …
=> DEVTOOLING-966: Validating that the schedule start date matches the rrule

genesyscloud/telephony_providers_edges_site/genesyscloud_telephony_providers_edges_site_proxy.go, genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site.go, genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_utils.go, genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route.go
Only update the Default Outbound Route if it's a Cloud based site (since the GC only auto creates the default outbound route for a cloud based site)
=> Fix DEVTOOLING-936 (update)

docs/resources/outbound_campaign.md, docs/resources/outbound_messagingcampaign.md, genesyscloud/outbound/genesyscloud_outbound_messagingcampaign_schema.go, genesyscloud/outbound/resource_genesyscloud_outbound_messagingcampaign.go, genesyscloud/outbound_campaign/resource_genesyscloud_outbound_campaign.go, genesyscloud/outbound_campaign/resource_genesyscloud_outbound_campaign_schema.go, genesyscloud/outbound_campaign/resource_genesyscloud_outbound_campaign_test.go
Doing this to avoid plan output because the ordering of the list changed. TypeSet ignores ordering, TypeList does not
Addresses [this forum post](https://developer.genesys.cloud/forum/t/outbound-campaign-dnc-list-showing-changes-even-when-nothing-added-deleted/30949/2)
=> NO-JIRA: converting from TypeList to TypeSet

genesyscloud/tfexporter/export_common.go, genesyscloud/tfexporter/genesyscloud_resource_exporter.go, genesyscloud/tfexporter/genesyscloud_resource_exporter_test.go, genesyscloud/tfexporter/hcl_exporter.go, genesyscloud/tfexporter/json_exporter.go, genesyscloud/util/lists/util_lists.go
Addresses an issue where the state for duplicated resources was not getting updated due to the separate handling of HCL and JSON maps, when we really should just handle the resource/data maps as one object that the HCL/JSON exporter iterates over and exports in the proper format. Also, as an added bonus, I added sorting of the output to make things more consistent on outputs. I have seen this as a request from both internal and customers
=> Fixes DEVTOOLING-988

genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route.go
Only attempt to update the default outbound route if it already exists; if not, go ahead and create it
This was found while working through telephony support in the BCP Wizard
=> NOJIRA - Default Outbound Routes Creation Logic Tweak

docs/resources/telephony_providers_edges_site_outbound_route.md, examples/resources/genesyscloud_telephony_providers_edges_site_outbound_route/apis.md, genesyscloud/telephony_providers_edges_site_outbound_route/genesyscloud_telephony_providers_edges_site_outbound_route_proxy.go
This is to fix a bug where the output of the outbound routes would return the same outbound routes as the previous site if the same number of routes was returned. This was discovered while testing telephony support for the BCP Wizard.
This caching logic was obviously copied over from the site resource, where it should remain. But it is not appropriate for this resource.
Also fixes an issue where a cache collision could occur (unlikely but important to address)
=> NOJIRA - Fix/outbound route cache

genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site.go
Happened across this NPE in Razorcrest
```
Stack trace from the terraform-provider-genesyscloud plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x45b0b30]
goroutine 213 [running]:
terraform-provider-genesyscloud/genesyscloud/telephony_providers_edges_site.updateSite.func1()
/Users/bgoad/genesys/git/terraform-provider-genesyscloud/genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site.go:275 +0x490
terraform-provider-genesyscloud/genesyscloud/util.RetryWhen(0x4ff6200, 0xc000de6f40, {0x0, 0x0, 0x0})
/Users/bgoad/genesys/git/terraform-provider-genesyscloud/genesyscloud/util/util_retries.go:63 +0xb4
terraform-provider-genesyscloud/genesyscloud/telephony_provid …
```
=> NOJIRA - Fix NPE

jenkins/release/Jenkinsfile
Sometimes the build fails because the `chmod` command is executed before the `cp`. This is because `&` means runs the first command in the background and move right onto the second. Changing to `&&` will fix the problem as it means only run the second command if the first is successful.
=> No JIRA: Slight change to commands in release build to prevent race condition.

docs/resources/routing_queue_conditional_group_routing.md, genesyscloud/routing_queue/resource_genesyscloud_routing_queue_utils.go, genesyscloud/routing_queue_conditional_group_routing/genesyscloud_routing_queue_conditional_group_routing_utils.go, genesyscloud/routing_queue_conditional_group_routing/resource_genesyscloud_routing_queue_conditional_group_routing.go, genesyscloud/routing_queue_conditional_group_routing/resource_genesyscloud_routing_queue_conditional_group_routing_schema.go, genesyscloud/routing_queue_conditional_group_routing/resource_genesyscloud_routing_queue_conditional_group_routing_unit_test.go
After converting to TypeSet, the function `TestResourceDataRaw` in the schema package was failing and causing those unit tests to fail. In the end, I just scrapped them and wrote new unit tests for the build and flatten functions.
=> DEVTOOLING-929: Converting groups in CGR rules.groups from TypeList to TypeSet

genesyscloud/routing_queue/data_source_genesyscloud_routing_queue.go, genesyscloud/routing_queue/genesyscloud_routing_queue_proxy.go, genesyscloud/routing_queue/resource_genesyscloud_routing_queue.go, genesyscloud/routing_queue_conditional_group_routing/resource_genesyscloud_routing_queue_conditional_group_routing.go, genesyscloud/routing_queue_outbound_email_address/resource_genesyscloud_routing_queue_outbound_email_address.go
This PR changes the export for queues to account for queues with peer_id, using the hasPeer flag in the API call
=> [Devtooling-834] hasPeer Not exported

genesyscloud/telephony_provider_edges_trunkbasesettings/data_source_genesyscloud_telephony_providers_edges_trunkbasesettings.go, genesyscloud/telephony_provider_edges_trunkbasesettings/data_source_genesyscloud_telephony_providers_edges_trunkbasesettings_test.go, genesyscloud/telephony_provider_edges_trunkbasesettings/resource_genesyscloud_telephony_providers_edges_trunkbasesettings.go
The data source read function for trunkbase settings was only retrying for 1 second and there was no condition where it would return a retryable error
=> No jira: Fix trunkbase setting data source test failure

genesyscloud/routing_queue/resource_genesyscloud_routing_queue_schema.go
Provider 1.61.0
Queue canned response libraries currently get exported with hard-coded IDs instead of references to terraform resource "genesyscloud_responsemanagement_library"
Current export data:
resource "genesyscloud_routing_queue" "NL_C_DEFAULT_Q1" {
canned_response_libraries {
library_ids = ["abab5121-4b40-4e25-86e0-814d3b7a8f58", "a6cacb4f-ac6f-40a0-b1a2-272cc35fe7b0", "e1e57682-e75e-472a-be5b-a340b1b7ce25"]
mode = "SelectedOnly"
}
After the fix:
resource "genesyscloud_routing_queue" "NL_C_DEFAULT_Q1" {
canned_response_libraries {
library_ids = ["${genesyscloud_responsemanagement_library.ESI_NL_Jaarwissel.id}", "${genesyscloud_responsemanagement_library.ESI_NL_English.id}", "${genesyscloud_responsemanagement_library.ESI_NL_Nederlands.id}"]
mode = "SelectedOnly"
}
=> Fixed the reference to Canned Response Libraries in the RoutingQueueExporter function

genesyscloud/architect_ivr/resource_genesyscloud_architect_ivr_schema.go
Provider 1.61.0
The issue is related to resource "genesyscloud_architect_ivr" field "dnis" being set as "Computed = true". When not available in the Terraform configuration, this field retrieves its value from the state. This prevents phone numbers from being transferred between IVRs as the dnis must be unique and not in use by another resource.
**Error:**
Failed to create IVR config IVR_PROD error: error performing create inside function uploadArchitectIvrWithChunkingLogic: API Error: 400 - PhoneNumber with text '+33173290933' already exists.
**Scenario:**
- Org A has IVR_DEV configured with dnis "+33173290933"
- Org B has IVR_DEV configured with dnis "+33173290933"
- GC admin manually removes the dnis "+33173290933" from IVR_DEV on Org A, and configures the same dnis for IVR_PROD on …
=> Architect IVR dnis computed issue

genesyscloud/provider/sdk_client_pool.go
Fixes https://inindca.atlassian.net/browse/DEVTOOLING-1175
Reorder structs to ensure proper alignment, specifically for 32-bit systems. 
Some details from Amazon Q:
> On 32-bit systems, the struct fields need to be ordered carefully to ensure proper alignment for atomic operations. Go ensures proper alignment of the first field in a struct, and by putting the 64-bit fields first, we guarantee they'll be properly aligned for atomic operations. The Go compiler will ensure the struct starts at an 8-byte boundary, and since the 64-bit fields are first, they're guaranteed to maintain that alignment. This ensures atomic operations on these fields will work correctly.
> The key principles to apply:
> 1. Put 64-bit fields first
> 2. Group fields by size (64-bit, 32-bit, 16-bit, 8-bit)
> 3. Put …
=> DEVTOOLING-1175 - Fix Unaligned Atomic Operations

genesyscloud/routing_queue/resource_genesyscloud_routing_queue_members.go, genesyscloud/routing_queue/resource_genesyscloud_routing_queue_members_test.go, genesyscloud/util/util_retries.go
Fixes DEVTOOLING-1170 by ensuring there is a retry when updating the queue member's ring. Adds some tests to confirm this.
=> DEVTOOLING-1170 - Ensures there is a retry when updating the queue member's ring

genesyscloud/architect_flow/resource_genesyscloud_flow.go, genesyscloud/integration/resource_genesyscloud_integration.go, genesyscloud/integration_action/resource_genesyscloud_integration_action.go, genesyscloud/knowledge_document/resource_genesyscloud_knowledge_document.go, genesyscloud/resource_exporter/resource_exporter.go, genesyscloud/resource_exporter/resource_name_sanitizer.go, genesyscloud/resource_exporter/resource_name_sanitizer_test.go, genesyscloud/responsemanagement_response/resource_genesyscloud_responsemanagement_response.go, genesyscloud/responsemanagement_responseasset/resource_genesyscloud_responsemanagement_responseasset.go, genesyscloud/telephony_providers_edges_did_pool/resource_genesyscloud_telephony_providers_edges_did_pool.go, genesyscloud/tfexporter/genesyscloud_resource_exporter.go, genesyscloud/user/resource_genesyscloud_user.go, genesyscloud/util/hash.go, genesyscloud/util/hash_test.go
This addresses DEVTOOLING-1183
We have several resource types that can still generate duplicate resource block labels. This addresses the issue by allowing the BCP Sanitizer to add a hash of the resource instance's unique fields to the block label. 
This should ensure consistency when comparing across orgs.
=> Feature/devtooling 1183 - Add support to BCP Sanitizer for including a hash of unique fields in the block label

genesyscloud/util/lists/util_lists.go, genesyscloud/util/lists/util_lists_test.go
Andrew Appleton reported this error:
```
Stack trace from the terraform-provider-genesyscloud_v1.63.0 plugin:
panic: interface conversion: interface {} is nil, not string
goroutine 338 [running]:
terraform-provider-genesyscloud/genesyscloud/util/lists.InterfaceListToStrings(...)
terraform-provider-genesyscloud/genesyscloud/util/lists/util_lists.go:130
terraform-provider-genesyscloud/genesyscloud/util/lists.BuildSdkStringListFromInterfaceArray(0xc00052bd00, {0x1aa9aab, 0xc})
terraform-provider-genesyscloud/genesyscloud/util/lists/util_lists.go:157 +0x138
terraform-provider-genesyscloud/genesyscloud/idp_generic.updateIdpGeneric({0x1f0e180, 0xc000b676c0}, 0xc00052bd00, {0x16e83a0, 0xc00014bc20})
terraform-provider-genesyscloud/genesyscloud/idp_generic/resource_genesyscloud_idp_generic.go:110 …
```
=> Util list hardening to prevent nil dereference panics

genesyscloud/routing_queue/resource_genesyscloud_routing_queue_schema.go
I could not find the PR request where this change was made, but between v1.62.0 and v1.63.0 the Computed flag was removed from `members` in the routing queue resource. This needs to be Computed so that queue members can be managed separately/outside of Terraform.
=> (NO-JIRA) genesyscloud_routing_queue: Fixes issue #1705

docs/resources/organization_presence_definition.md, genesyscloud/organization_presence_definition/resource_genesyscloud_organization_presence_definition_schema.go
While trying to recreate another export bug, I caught a few instances where the validator functions in the new presence definition resource was producing plan errors e.g. `expected system_presence to be one of [...] got "abc"`
To fix this I removed the validators. I think it is better to list the known valid options in the descriptions and leave the validation up to the API.
=> (NO-JIRA) genesyscloud_organization_presence_definition: Removing validators to fix export

genesyscloud/architect_ivr/resource_genesyscloud_architect_ivr.go
Since the BlockLabel for genesyscloud_architect_ivr is a concatenation of the ivr's name and OpenHoursFlow's name, if the resource is exported and applied to a new org and then the OpenHoursFlow changes in the original, during any subsequent export and apply terraform will attempt to create a new resource with that different label but the same id and name and throw an api error.
=> [Devtooling-1131] genesyscloud_architect_ivr remove OpenHoursFlow from BlockLabel

docs/guides/export.md, templates/guides/export.md.tmpl
The `diff` code block was all messed up in the terraform registry, so I changed it to `hcl`
https://registry.terraform.io/providers/MyPureCloud/genesyscloud/latest/docs/guides/export
=> (NO-JIRA) Small change to export guide

genesyscloud/responsemanagement_response/resource_genesyscloud_responsemanagement_response.go
Since responses can have the same name this is to stop the exporter from having run to run variance when exporting responses with the same name but different libraries.
=> [Devtooling-1235] 'genesyscloud_responsemanagement_response' Adding library name to BlockLabel

genesyscloud/outbound_contact_list/resource_genesyscloud_outbound_contact_list_utils.go, genesyscloud/user/genesyscloud_user_proxy.go
* DEVTOOLING-991 introduced an extra API call to the export of users; [GET /api/v2/routing/users/{userId}/utilization](https://developer.genesys.cloud/devapps/api-explorer#get-api-v2-routing-users--userId--utilization). This almost doubles the export time for users because the endpoint is sensitive to rate-limiting. Removing the singleton pattern in the proxy file addressed this. 
* The main cause of the export time increase was the work done for DEVTOOLING-1191. Sometimes the download URL for a contact list export would take some time generate (if the list is huge), so a sleep was introduced. The mistake was sleeping for 30 seconds even before making the API call. So a 30 second sleep occurred for each contact list and 600 * 30 seconds is 5 hours.
=> (DEVTOOLING-1230) Addressed the issue of increased export times 

genesyscloud/util/feature_toggles/bcp_running.go, genesyscloud/util/util_e164.go, genesyscloud/util/util_e164_test.go, genesyscloud/validators/validators.go
Fixes phone number validator logic, and adds a BCP enabled mode flag that can bypass the validation logic
=> fix: DEVTOOLING-1280 by fixing phone number validator

genesyscloud/knowledge_document/resource_genesyscloud_knowledge_document_schema.go, genesyscloud/resource_exporter/resource_exporter_custom.go
This custom resolver makes the label names a reference to the name of the label resource itself the same way the [documentation example](https://registry.terraform.io/providers/MyPureCloud/genesyscloud/latest/docs/resources/knowledge_document) sets it. This will ensure when exporting from one org then applying the knowledge resources elsewhere the creation/update order is correct.
Without this the labels are exported as strings, and when applied if the document is created before the label, knowledge_document.label_names will not be set and cause the consistency checker to fail.
=> [Devtooling-1209] custom resolver for 'genesyscloud_knowledge_document' label_names

genesyscloud/outbound_contact_list/genesyscloud_outbound_contact_list_proxy.go, genesyscloud/outbound_contact_list/resource_genesyscloud_outbound_contact_list.go, genesyscloud/outbound_contact_list/resource_genesyscloud_outbound_contact_list_test.go
https://inindca.atlassian.net/browse/DEVTOOLING-1379
Sample output when a failed import is detected:
```
genesyscloud_outbound_contact_list.CSCh_RIC_CAP_Blast_Special: Creating...
╷
│ Error: Failed to upload contacts to contact list (eaa1d6cc-c066-4034-8cd3-41b486ada0c3) due to CONTACT_COLUMNS_LIMIT_EXCEEDED
│ {"resourceType":"genesyscloud_outbound_contact_list","method":"GET","path":"/api/v2/outbound/contactlists/eaa1d6cc-c066-4034-8cd3-41b486ada0c3/importstatus","statusCode":200,"correlationId":"874df792-bc8b-4a37-8c8b-5265169529a1"}
│ 
│ 
│   with genesyscloud_outbound_contact_list.CSCh_RIC_CAP_Blast_Special,
│   on main.tf line 1, in resource "genesyscloud_outbound_contact_list" "CSCh_RIC_CAP_Blast_Special":
│    1: resource "genesyscloud_outbound_contact_list" …
```
=> Fixes DEVTOOLING-1379 by detecting contact list import errors
