genesyscloud/resource_genesyscloud_routing_queue.go
Update queue timeout maximum to 259200 seconds (3 days)
=> Update queue timeout maximum

.github/workflows/test.yml, docs/resources/tf_export.md, examples/resources/genesyscloud_tf_export/resource.tf, genesyscloud/resource_exporter.go, genesyscloud/resource_genesyscloud_routing_queue.go, genesyscloud/resource_genesyscloud_tf_export.go, genesyscloud/resource_genesyscloud_tf_export_test.go, genesyscloud/resource_genesyscloud_user.go, genesyscloud/util_lists.go
Allowing exporting resources by name using `resource_type::resource_name` syntax
=> feat/cxcode 50 - export by name

.github/workflows/generate.yml, genesyscloud/resource_genesyscloud_user.go, genesyscloud/resource_genesyscloud_user_test.go, main.go
The user API usually returns a "display value" for numbers instead of extension + number which they are created with. This workaround is a best effort for dealing with this
Also added a pipeline step to make sure documentation stays in sync with resources
=> CXCODE-114 - Workaround for user number and extension values

docs/resources/integration_action.md, genesyscloud/resource_genesyscloud_integration_action.go
DELETE was added in PURE-3253.
=> Fix data action resource to allow DELETE method

genesyscloud/resource_exporter.go, genesyscloud/resource_genesyscloud_architect_datatable_row.go, genesyscloud/resource_genesyscloud_integration.go, genesyscloud/resource_genesyscloud_integration_action.go, genesyscloud/resource_genesyscloud_telephony_providers_edges_phonebasesettings.go, genesyscloud/resource_genesyscloud_telephony_providers_edges_trunkbasesettings.go, genesyscloud/resource_genesyscloud_tf_export.go
[https://inindca.atlassian.net/browse/DEVENGAGE-1054](https://inindca.atlassian.net/browse/DEVENGAGE-1054)
=> [DEVENGAGE-1054] Adding logic to export json strings as jsonencode objects

genesyscloud/resource_genesyscloud_routing_queue_test.go
Making some unreachable code reachable
=> [no jira] Small refactoring in queues resource tests

docs/resources/tf_export.md, genesyscloud/resource_genesyscloud_tf_export.go
=> DEVENGAGE-1402: Small update to tf_export resource docs.

.github/workflows/release.yml
[https://github.com/MyPureCloud/terraform-provider-genesyscloud/actions/runs/4135919329/jobs/7149037274](https://github.com/MyPureCloud/terraform-provider-genesyscloud/actions/runs/4135919329/jobs/7149037274)
=> Small change to release.yml

.github/workflows/release.yml
Details of the bug and fix can be found here - [https://github.com/actions/runner-images/issues/6709#issuecomment-1361269639](https://github.com/actions/runner-images/issues/6709#issuecomment-1361269639)
=> Updating ubuntu version in release.yml

docs/resources/journey_action_map.md, genesyscloud/resource_genesyscloud_journey_action_map.go, genesyscloud/resource_genesyscloud_journey_action_map_test.go, genesyscloud/util_lists.go, test/data/resource/genesyscloud_journey_action_map/action_media_types/01_create_web_messaging_offer_without_config.tf, test/data/resource/genesyscloud_journey_action_map/action_media_types_with_trigger_conditions/01_create_web_messaging_offer_with_trigger_event_condition.tf, test/data/resource/genesyscloud_journey_action_map/action_media_types_with_trigger_conditions/02_update_web_messaging_offer_with_trigger_event_condition.tf, test/data/resource/genesyscloud_journey_action_map/basic_optional_attributes/07_update_remove_trigger_with_segments.tf
There're two changes in this PR
1. Added `is_pacing_enabled` feature the action-map 
2. `trigger_with_segments` is now an optional parameter
3. Updated document using `go generate` and tests
=> GPE-12605: Added is_pacing_enabled & trigger_with_segments is an optional parameter

genesyscloud/provider.go, test/data/resource/genesyscloud_journey_action_map/action_media_types_with_trigger_conditions/02_update_web_messaging_offer_with_trigger_event_condition.tf
Error message that was coming from `TestAccResourceJourneyActionMapActionMediaTypesWithTriggerConditions`:
```
Key 'page.titleChanged' is invalid for event type page_viewed`
```
=> [no-jira] action journey map test fix and removed log statement

genesyscloud/resource_genesyscloud_script.go
Script names do not have to be unique, so I implemented some logic in the resource create function to check if a script already exists with that name. My mistake was assuming the `name` parameter in [GET /api/v2/scripts](https://developer.genesys.cloud/devapps/api-explorer#get-api-v2-scripts) performed direct comparison. It actually returns any script that partially matches the value. So `name='test'` could return script `test`, `test_v1`, `test_script`, etc.
=> Fixed bug in scripts creation

docs/resources/outbound_campaignrule.md, docs/resources/outbound_sequence.md, genesyscloud/resource_genesyscloud_outbound_campaignrule.go, genesyscloud/resource_genesyscloud_outbound_campaignrule_test.go, genesyscloud/resource_genesyscloud_outbound_sequence.go, genesyscloud/resource_genesyscloud_outbound_sequence_test.go
This PR fixes https://inindca.atlassian.net/browse/DEVENGAGE-1923
=> Fix DEVENGAGE-1923 - Enable campaign rules / sequences from the point of creation

docs/resources/webdeployments_configuration.md, genesyscloud/resource_genesyscloud_webdeployments_configuration.go
Details about the change in https://inindca.atlassian.net/browse/DEVENGAGE-1930
Want to make sure this change does not effect any existing users who are using the webdeployment. 
Any thoughts welcome..
=> make sure version is solely computed and not user provided

docs/resources/webdeployments_configuration.md, examples/resources/genesyscloud_webdeployments_configuration/resource.tf, genesyscloud/resource_genesyscloud_webdeployments_configuration.go, genesyscloud/resource_genesyscloud_webdeployments_configuration_test.go
Added channels to cobrowse settings.
=> DEVENGAGE-2030 cobrowse channels

genesyscloud/resource_exporter/resource_exporter.go, genesyscloud/resource_genesyscloud_routing_queue.go, genesyscloud/resource_genesyscloud_routing_skill_group.go, genesyscloud/resource_genesyscloud_telephony_providers_edges_site.go, genesyscloud/test_utils.go, genesyscloud/tfexporter/export_common.go, genesyscloud/util/lists/util_lists.go, genesyscloud/validators.go
This change doesn't actually reduce the lines of code *yet*. Just getting familiar with generics
=> [no-jira] Small refactoring towards generics

docs/resources/webdeployments_configuration.md, genesyscloud/data_source_genesyscloud_webdeployments_deployment_test.go, genesyscloud/resource_genesyscloud_webdeployments_configuration.go, genesyscloud/resource_genesyscloud_webdeployments_configuration_test.go, genesyscloud/resource_genesyscloud_webdeployments_deployment_test.go
This fixes the test failures `API Error: 400 - Unable to perform the requested operation`
=> Making 'languages' and 'default_language' Required in WD config resource

genesyscloud/resource_genesyscloud_flow.go
There was an issue in the flows resource where a user would:
- Successfully deploy a flow
- Change something in the yaml file and make it invalid
- Re-run `terraform apply` , the apply would fail
- Re-run `terraform apply` again, no changes would be detected in the file (because there were none) and `No changes. Apply complete.` would display in green
I noticed this didn't happen with the scripts resource because all fields were `ForceNew` and no UpdateContext was used, only Create. This means the existing script would be destroyed before trying to re-upload with an invalid script. Running `terraform apply` after this would mean an attempt at a create, not an update. 
On the other hand, the flows resource had a create and update function, but the create always just ran right into the …
=> Avoiding UpdateContext for flows resource

genesyscloud/resource_genesyscloud_webdeployments_deployment.go
Added additional timeout before checking if a webdeployment became active.
=> DEVENGAGE-2089 additional timeout for deployment to become active

GNUmakefile, genesyscloud/tfexporter/export_common.go, genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
Add a check to filter functions so that the regex will only be applied to the correct resource.
EDIT: Also added test cases for the scenarios
=> DEVENGAGE-2106 Fix regex applying to all resource exporters

genesyscloud/resource_genesyscloud_knowledge_v1_category_test.go, genesyscloud/resource_genesyscloud_knowledge_v1_document_test.go
Commenting out knowledge v1 tests which were somehow generated requests in prod despite the `t.Skip()` lines
=> DEVENGAGE-2126 Comment out knowledge v1 tests

genesyscloud/resource_exporter/resource_exporter.go, genesyscloud/resource_exporter/resource_exporter_test.go
Reverts MyPureCloud/terraform-provider-genesyscloud#653
=> Revert "[DEVENGAGE-2189] Only add a random suffix on export to resources that have been sanitized with the same matching name pattern"

genesyscloud/resource_genesyscloud_user.go
- Coroutines send data to channel instead of accessing resource map directly
- Create anonymous function for getting users based on status
=> DEVENGAGE-2064 Fix getAllUsers map concurrency issue

genesyscloud/resource_genesyscloud_user.go
=> DEVTOOLING-58: Make getAllUsers synchronous

.gitignore, Jenkinsfile
Reverts MyPureCloud/terraform-provider-genesyscloud#717
=> Revert "Jenkinstest"

genesyscloud/integration/data_source_genesyscloud_integration.go, genesyscloud/integration/genesyscloud_integration_proxy.go, genesyscloud/integration/resource_genesyscloud_integration.go, genesyscloud/integration_credential/genesyscloud_integration_credential_proxy.go, genesyscloud/integration_credential/resource_genesyscloud_integration_credential.go
Reverts MyPureCloud/terraform-provider-genesyscloud#755
=> Revert "DEVTOOLING-282"

genesyscloud/task_management_worktype/resource_genesyscloud_task_management_worktype_unit_test.go, genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
Few small things that needed to be changed when updating from v116 to v119, but weren't
=> No jira: Fixing issues introduced by update to v119

.github/workflows/test-workflow.yml, .github/workflows/test.yml, genesyscloud/architect_ivr/data_source_genesyscloud_architect_ivr_test.go, genesyscloud/data_source_genesyscloud_journey_action_map_test.go, genesyscloud/data_source_genesyscloud_journey_action_template_test.go, genesyscloud/data_source_genesyscloud_journey_outcome_test.go, genesyscloud/data_source_genesyscloud_journey_segment_test.go, genesyscloud/provider.go, genesyscloud/resource_genesyscloud_responsemanagement_responseasset_test.go, genesyscloud/tfexporter/genesyscloud_resource_exporter_test.go
A few changes to make sure all tests are being ran and that all possible artefacts are being uploaded.
=> No jira: organising test names

genesyscloud/validators.go
=> DEVTOOLING-360: fixed rrule validation

genesyscloud/provider.go
Allows users to specify the location where the log file will be created and creates the filepath specified if not already exists
=> DEVTOOLING-351: Defined sdk_debug_file_path for log file location

genesyscloud/architect_schedulegroups/resource_genesyscloud_architect_schedulegroups.go, genesyscloud/architect_schedulegroups/resource_genesyscloud_architect_schedulegroups_schema.go
Fixes an issue introduced by DEVTOOLING-148 by bringing back the export code for Architect Schedule Groups
=> Fixes an issue introduced by DEVTOOLING-148 

docs/resources/telephony_providers_edges_phone.md, genesyscloud/telephony/resource_genesyscloud_telephony_providers_edges_trunkbasesettings.go, genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone.go, genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone_schema.go, genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone_test.go, genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone_utils.go, genesyscloud/telephony_providers_edges_phonebasesettings/resource_genesyscloud_telephony_providers_edges_phonebasesettings.go, genesyscloud/util/util_basesetting_properties.go
Reverts MyPureCloud/terraform-provider-genesyscloud#874
=> Revert "Devtooling 287"

.goreleaser.yml
Reverts MyPureCloud/terraform-provider-genesyscloud#897
=> Revert "no-jira: Commenting out goreleaser temporarily to run jenkins build"

genesyscloud/team/genesyscloud_team_proxy.go, genesyscloud/team/resource_genesyscloud_team.go, genesyscloud/team/resource_genesyscloud_team_test.go, genesyscloud/team/resource_genesyscloud_team_utils.go
If we tried to add members to a team that was created without members nothing was happening. I removed the if statement causing this. There was situations in the read where we weren't updating the member_ids state which is how this issue wasn't showing up. I also found a similar problem trying to delete all members from a team
=> Devtooling 561 - Members not being added correctly to teams

genesyscloud/station/data_source_genesyscloud_station_test.go, genesyscloud/telephony_providers_edges_phone/data_source_genesyscloud_telephony_providers_edges_phone_test.go, genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone.go, genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone_test.go, genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone_utils.go
Reverts MyPureCloud/terraform-provider-genesyscloud#1015
=> Revert "bug/devtooling 560 - Nil error in telephony_providers_edges_phone"

genesyscloud/resource_genesyscloud_quality_forms_evaluation.go
A test was failing due to https://github.com/MyPureCloud/terraform-provider-genesyscloud/pull/1022 as it was not allowing `published = true` to be changed to false. This is overcome but checking if the operation is during an export and assigning the published attribute accordingly
=> No-Jira - fixing test for published attribute

genesyscloud/auth_role/genesyscloud_auth_role_proxy.go, genesyscloud/external_contacts/genesyscloud_externalcontacts_contact_proxy.go, genesyscloud/telephony_providers_edges_phone/genesyscloud_telephony_providers_edges_phone_proxy.go
Implement caching for the following packages :
auth_role
external_contacts
telephony_providers_edges_phone
=> added caching capabilities

genesyscloud/telephony/resource_genesyscloud_telephony_providers_edges_trunkbasesettings.go, genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site.go, genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route_schema.go, genesyscloud/util/feature_toggles/outbound_routes.go
Fix issues identified in DEVTOOLING-662 as a result of testing DEVTOOLING-477
=> Fix issues identified in DEVTOOLING-662 

genesyscloud/data_source_genesyscloud_routing_skill_group.go, genesyscloud/data_source_genesyscloud_routing_skill_group_test.go, genesyscloud/resource_genesyscloud_routing_skill_group.go
There were some mistakes in the skill group data source logic and in the exporter. The SDK methods must have been released since that code was written, so I converted from raw HTTP to using the SDK.
=> no jira: Fixes #1086 + some minor refactoring

docs/resources/routing_queue.md, genesyscloud/routing_queue/genesyscloud_routing_queue_init_test.go, genesyscloud/routing_queue/resource_genesyscloud_routing_queue.go, genesyscloud/routing_queue/resource_genesyscloud_routing_queue_schema.go, genesyscloud/routing_queue/resource_genesyscloud_routing_queue_test.go
Implement onHoldPrompt on routingqueue resource
=> feat/DEVTOOLING-602 onHoldPrompt attribute 

genesyscloud/resource_genesyscloud_knowledge_knowledgebase.go
genesyscloud_knowledge_knowledgebase core_langage support for ja-JP
=> feat/devtooling 632 added validation for ja-JP

docs/resources/user.md, examples/resources/genesyscloud_user/apis.md, genesyscloud/group/resource_genesyscloud_group_utils.go, genesyscloud/resource_genesyscloud_init_test.go, genesyscloud/resource_genesyscloud_location.go, genesyscloud/resource_genesyscloud_user.go, genesyscloud/resource_genesyscloud_user_test.go, genesyscloud/telephony_providers_edges_extension_pool/data_source_genesyscloud_telephony_providers_edges_extension_pool.go, genesyscloud/telephony_providers_edges_extension_pool/data_source_genesyscloud_telephony_providers_edges_extension_pool_test.go, genesyscloud/telephony_providers_edges_extension_pool/genesyscloud_telephony_providers_edges_extension_pool_schema.go, genesyscloud/telephony_providers_edges_extension_pool/resource_genesyscloud_telephony_providers_edges_extension_pool.go, genesyscloud/telephony_providers_edges_extension_pool/resource_genesyscloud_telephony_providers_edges_extension_pool_test.go, genesyscloud/telephony_providers_edges_extension_pool/resource_genesyscloud_telephony_providers_edges_extension_pool_utils.go, genesyscloud/util/feature_toggles/user_addresses.go, genesyscloud/util/util_e164.go, genesyscloud/validators/validators.go
Fixes DEVTOOLING-675 by updating the logic for returning user addresses.  This is kept behind the feature flag USE_NEW_USER_ADDRESS_LOGIC env variable to prevent backwards compatibility issues. This commit also refactors a few things for unit testing.
Example comparing portions of two state files of an export of the environment under test in Japan, first one before, second one after using new logic:
```
"addresses.0.phone_numbers.2899191931.extension": "1200",
"addresses.0.phone_numbers.2899191931.media_type": "PHONE",
**"addresses.0.phone_numbers.2899191931.number": "1200",**
"addresses.0.phone_numbers.2899191931.type": "WORK2",
"addresses.0.phone_numbers.3516972489.extension": "1997",
"addresses.0.phone_numbers.3516972489.media_type": "PHONE", …
```
=> Fixes DEVTOOLING-675 

DEBUGGING.md, README.md, main.go
Inspired by a discussion with @carnellj earlier today
=> Fix debugging issue and add docs on how to setup debugging

genesyscloud/outbound_ruleset/resource_genesyscloud_outbound_ruleset.go, genesyscloud/provider/provider.go, genesyscloud/resource_exporter/resource_exporter_custom.go
This PR
Will remove the filter of rulesets based on skill set existence.
Instead it will filter the skills being referenced i they are not existent. 
The rulesets will still be present.
=> Ruleset and Skill Resource

docs/resources/responsemanagement_responseasset.md, genesyscloud/responsemanagement_responseasset/resource_genesyscloud_responsemanagement_responseasset_schema.go, genesyscloud/validators/validators.go
genesyscloud_responsemanagement_responseasset exports filenames with spaces
=> bug/Devtooling 723 - exports filenames with spaces

.github/workflows/pr-labeler.yml
Add required permissions to PR Labeler (see https://github.com/TimonVS/pr-labeler-action?tab=readme-ov-file#usage )
=> Add required permissions to PR Labeler 

docs/resources/tf_export.md, genesyscloud/integration_action/resource_genesyscloud_integration_action_schema.go, genesyscloud/tfexporter/genesyscloud_resource_exporter.go, genesyscloud/tfexporter/resource_genesyscloud_tf_export.go
Fixes DEVTOOLING-855 Add provider attribute to determine whether to export computed attributes or not
=> Fix DEVTOOLING-855 - option for exporting computed values

docs/data-sources/flow.md, genesyscloud/architect_flow/data_source_genesyscloud_flow.go, genesyscloud/architect_flow/data_source_genesyscloud_flow_test.go, genesyscloud/architect_flow/resource_genesyscloud_architect_flow_proxy.go, genesyscloud/architect_flow/resource_genesyscloud_architect_flow_schema.go, genesyscloud/architect_flow/resource_genesyscloud_flow.go, genesyscloud/routing_queue/data_source_genesyscloud_routing_queue.go, genesyscloud/routing_queue/genesyscloud_routing_queue_proxy.go, genesyscloud/routing_skill/data_source_genesyscloud_routing_skill.go, genesyscloud/routing_skill/genesyscloud_routing_skill_proxy.go
Changes:
* routing_queue data source 
* Fixed minor bugs and cleaned up code smells
* Removed sleep in hydrate function 
* Increased logging 
* architect_flow data source
* Added `type` to data source schema and started making use of name and varType query parameters to decrease number of API calls made per data source
* Increased logging 
* Improved tests
* routing_skill data source
* Increased logging and improved error handling
=> No jira: Improving the efficiency of a few data sources

docs/resources/idp_adfs.md, genesyscloud/idp_adfs/resource_genesyscloud_idp_adfs_schema.go
I removed the description for `idp_adfs.slo_binding`. My mistake merging the last PR without letting Hemanth's comment be addressed. 
@HemanthDogiparthi12 @BrianMoyles
=> No jira: adfs description

genesyscloud/oauth_client/resource_genesyscloud_oauth_client.go
Fixed the nil pointer dereference that caused the stack trace seen in Issue #1301 and also cleaned up a few other code smells/potential nil pointer reference errors
=> Fixes #1301 - Nil pointer dereference in oauth_client package 

genesyscloud/recording_media_retention_policy/resource_genesyscloud_recording_media_retention_policy_utils.go
Fixed test cases `TestAccResourceMediaRetentionPolicyBasic` and `TestAccDataSourceRecordingMediaRetentionPolicy`
=> No jira: Recording media retention policy test fix

.github/CODEOWNERS, docs/resources/responsemanagement_response.md, genesyscloud/responsemanagement_response/data_source_genesyscloud_responsemanagement_response_test.go, genesyscloud/responsemanagement_response/resource_genesyscloud_responsemanagement_response_schema.go, genesyscloud/responsemanagement_response/resource_genesyscloud_responsemanagement_response_test.go, genesyscloud/responsemanagement_response/resource_genesyscloud_responsemanagement_response_utils.go, genesyscloud/responsemanagement_responseasset/data_source_genesyscloud_responsemanagement_responseasset_test.go, genesyscloud/responsemanagement_responseasset/resource_genesyscloud_responsemanagement_responseasset_test.go, genesyscloud/responsemanagement_responseasset/resource_genesyscloud_responsemanagement_responseasset_utils.go, genesyscloud/util/testrunner/testrunner.go
This code changes must be merged after merging this PR https://github.com/MyPureCloud/terraform-provider-genesyscloud/pull/1304
=> code fix for DEVTOOLING-762

genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact.go, genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact_utils.go
Fixes hanging on export for contact_list_contacts in 1.50.0 due to oversights and lack of thorough testing of https://github.com/MyPureCloud/terraform-provider-genesyscloud/pull/1291
=> Fix DEVTOOLING-895

genesyscloud/knowledge_document/genesyscloud_knowledge_document_proxy.go, genesyscloud/resource_genesyscloud_knowledge_category.go, genesyscloud/resource_genesyscloud_knowledge_knowledgebase.go, genesyscloud/resource_genesyscloud_knowledge_label.go, genesyscloud/team/genesyscloud_team_proxy.go
**The issue described in the ticket DEVTOOLING-902 was not resolved in this PR**
=> DEVTOOLING-902: Fixed bugs in pagination logic across a few packages

genesyscloud/journey_views/data_source_genesyscloud_journey_view_test.go, genesyscloud/journey_views/genesyscloud_journey_views_proxy.go, genesyscloud/journey_views/resource_genesyscloud_journey_views.go, genesyscloud/journey_views/resource_genesyscloud_journey_views_schema.go, genesyscloud/journey_views/resource_genesyscloud_journey_views_test.go, genesyscloud/journey_views/resource_genesyscloud_journey_views_utils.go
Reverts MyPureCloud/terraform-provider-genesyscloud#1371
This PR was merged right to main and broke the Go Checks workflow. Reverting until we get the release for v1.53.0 done. 
@nicob-29 Please re-open the PR with `dev` as the target branch and we will get it merged asap
=> Revert "WIP: JM-1645: Use Put about Update and add Charts"

DICTIONARY.md, README.md
Part 3 of https://inindca.atlassian.net/issues/DEVTOOLING-924
=> DEVTOOLING-924 pt3 - Add documentation regarding shared domain dictionary

genesyscloud/external_contacts_organization/data_source_genesyscloud_externalcontacts_organization_test.go, genesyscloud/external_contacts_organization/resource_genesyscloud_externalcontacts_organization.go, genesyscloud/external_contacts_organization/resource_genesyscloud_externalcontacts_organization_test.go
I started working on this package to fix the test case `TestAccResourceTfExportExcludeFilterResourcesByRegEx` but it was not as simple as I thought it would be and will take more investigating, so I created the ticket DEVTOOLING-977 
This PR only includes minor refactoring
=> No jira: externalcontacts org refactor

genesyscloud/architect_user_prompt/resource_genesyscloud_architect_user_prompt.go, genesyscloud/integration_custom_auth_action/data_source_genesyscloud_integration_custom_auth_action_test.go, genesyscloud/integration_custom_auth_action/resource_genesyscloud_integration_custom_auth_action_test.go, genesyscloud/journey_views/resource_genesyscloud_journey_views.go, genesyscloud/journey_views/resource_genesyscloud_journey_views_test.go
PR #1404 undid a few changes that were merged to dev since the last release. Probably during rebase "Incoming change" should have been selected over "Current change"
This PR re-introduces those changes
=> Fixing a few different test cases

genesyscloud/integration/resource_genesyscloud_integration.go, genesyscloud/integration/resource_genesyscloud_integration_utils.go, genesyscloud/integration_credential/resource_genesyscloud_integration_credential.go, genesyscloud/util/util_strings.go
Added new set of logs so that it will help in the future to further investigate this issues as it is unable to reproduce in the dev environment. 
---------------------
• Look for the log entry containing the keyword "Credentials details :", which provides the following information:
• Integration ID: <ID>
• Integration Name: <NAME>
• Credential ID: <ID>
• Credential Type: pureCloudOAuthClient
• Search for the log entry containing "Retrieving exporters list &" and check whether the filter list includes the Credential ID for the corresponding Integration. Ensure that the Credential ID is present in this filter list.
• Using the information from these two log entries, identify the Credential ID and Name, then map them to the relevant Integration. This will help determine the details retrieved …
=> DEVTOOLING-852 added logs

genesyscloud/architect_grammar_language/genesyscloud_architect_grammar_language_proxy.go, genesyscloud/architect_grammar_language/resource_genesyscloud_architect_grammar_language.go, genesyscloud/architect_grammar_language/resource_genesyscloud_architect_grammar_language_test.go, genesyscloud/architect_grammar_language/resource_genesyscloud_architect_grammar_language_utils.go, genesyscloud/architect_ivr/resource_genesyscloud_architect_ivr.go, genesyscloud/integration_credential/resource_genesyscloud_integration_credential.go, genesyscloud/knowledge/resource_genesyscloud_knowledge_document_variation.go, genesyscloud/knowledge_category/resource_genesyscloud_knowledge_category.go, genesyscloud/knowledge_document/resource_genesyscloud_knowledge_document.go, genesyscloud/knowledge_label/resource_genesyscloud_knowledge_label.go, genesyscloud/location/resource_genesyscloud_location.go, genesyscloud/outbound_contact_list_contact/genesyscloud_outbound_contact_list_contact_proxy.go, genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact.go, genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact_utils.go, genesyscloud/task_management_worktype_status/resource_genesyscloud_task_management_worktype_status.go, genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route.go
Fixes DEVTOOLING-981 by ensuring that the grammar name is included in the block label
=> Fixes DEVTOOLING-981 

genesyscloud/telephony_provider_edges_trunkbasesettings/resource_genesyscloud_telephony_providers_edges_trunkbasesettings.go, genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_schema.go, genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_utils.go, genesyscloud/util/lists/util_lists.go
Attempts to fix DEVTOOLING-967 by ensuring the exporter exports default number plans that always get create but might not get created due to updates made on the org.
=> Fix for DEVTOOLING-967

genesyscloud/architect_datatable_row/genesyscloud_architect_datatable_row_utils.go, genesyscloud/architect_datatable_row/resource_genesyscloud_architect_datatable_row.go, genesyscloud/architect_ivr/genesyscloud_architect_ivr_proxy.go, genesyscloud/architect_schedulegroups/genesyscloud_architect_schedulegroups_proxy.go, genesyscloud/architect_schedulegroups/resource_genesyscloud_architect_schedulegroups.go, genesyscloud/auth_role/data_source_genesyscloud_auth_role.go, genesyscloud/auth_role/genesyscloud_auth_role_proxy.go, genesyscloud/auth_role/resource_genesyscloud_auth_role.go, genesyscloud/auth_role/resource_genesyscloud_auth_role_test.go, genesyscloud/consistency_checker/consistency_checker.go, genesyscloud/conversations_messaging_integrations_open/genesyscloud_conversations_messaging_integrations_open_proxy.go, genesyscloud/conversations_messaging_supportedcontent_default/genesyscloud_conversations_messaging_supportedcontent_default_init_test.go, genesyscloud/conversations_messaging_supportedcontent_default/resource_genesyscloud_conversations_messaging_supportedcontent_default_schema.go, genesyscloud/resource_exporter/resource_name_sanitizer.go
Eventually it would be good to include the linter in the Go Checks workflow, so this is just a step towards that.
=> No jira: Fixed a few linting errors

genesyscloud/util/util_diagnostic_unit_test.go, genesyscloud/util/util_diagnostics.go
Reverts MyPureCloud/terraform-provider-genesyscloud#1479
=> Revert "tweak diagnostics"

genesyscloud/platform/platform.go, genesyscloud/platform/platform_test.go, genesyscloud/provider/provider.go, genesyscloud/tfexporter/genesyscloud_resource_exporter.go, genesyscloud/tfexporter/hcl_exporter.go, genesyscloud/tfexporter/json_exporter.go, genesyscloud/tfexporter/tfstate_exporter.go, genesyscloud/util/util_process.go, go.mod, go.sum
Fixed DEVTOOLING-1029 by adding support for detecting the binary executing the provider and including logical support for determining Terraform vs OpenTofu
Also happens to fix https://github.com/MyPureCloud/terraform-provider-genesyscloud/issues/1475 when `terraform` or `tofu` is not in the `PATH`
=> Fixes DEVTOOLING-1029

.goreleaser.yml
[link to deprecation notice](https://goreleaser.com/deprecations/#archivesformat)
=> No JIRA: heeding goreleaser deprecation warning

genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_utils.go, genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route.go
=> DEVTOOLING-1064 Fix telephony issues

genesyscloud/telephony_provider_edges_trunkbasesettings/genesyscloud_telephony_providers_trunkbasesettings_proxy.go, genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site.go
This is required for our Razorcrest product
=> Fixes DEVTOOLING-1066 - Trunkbasesettings cache hydrating

genesyscloud/platform/platform.go, genesyscloud/routing_queue/resource_genesyscloud_routing_queue_schema.go
Reference for direct_routing.backup_queue_id
=> [Devtooling-1062] Added exporter RefAttrs to routing queue

genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone.go, genesyscloud/telephony_providers_edges_phonebasesettings/resource_genesyscloud_telephony_providers_edges_phonebasesettings.go, genesyscloud/telephony_providers_edges_site/genesyscloud_telephony_providers_edges_site_proxy.go, genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site.go, genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route_schema.go, genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route_test.go, genesyscloud/util/test_utils.go, genesyscloud/util/util_retries.go
Fixes DEVTOOLING-1070 where a destroy can fail on read timeout
=> Fixing DEVTOOLING-1070 where destroy can fail on read timeout

genesyscloud/routing_email_route/genesyscloud_routing_email_route_proxy.go, genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route_utils.go
We have to do the filter for specific domain when fetching routing_email_route. the existing code fix to accommodate it. 
**Tested several times and got the same ID as expected after the fix:**
data.genesyscloud_routing_email_domain.cxascode_domain,[id=cxascode.mypurecloud.com]
data.genesyscloud_routing_email_route.data-suresh-routing_email_route,[id=a483bbe0-5b49-4ec4-b47e-855cc3e83319]
data.genesyscloud_routing_email_domain.cxascode_domain,[id=cxascode.mypurecloud.com]
data.genesyscloud_routing_email_route.data-suresh-routing_email_route,[id=a483bbe0-5b49-4ec4-b47e-855cc3e83319]
data.genesyscloud_routing_email_domain.cxascode_domain,[id=cxascode.mypurecloud.com]
data.genesyscloud_routing_email_route.data-suresh-routing_email_route,[id=a483bbe0-5b49-4ec4-b47e-855cc3e83319] …
=> fix for DEVTOOLING-1091

docs/resources/routing_queue.md, examples/resources/genesyscloud_flow/inboundcall_flow_example.yaml, examples/resources/genesyscloud_flow/inboundcall_flow_example2.yaml, examples/resources/genesyscloud_flow/inboundcall_flow_example3.yaml, genesyscloud/routing_queue/resource_genesyscloud_routing_queue_schema.go, genesyscloud/routing_queue/resource_genesyscloud_routing_queue_test.go, genesyscloud/routing_queue/resource_genesyscloud_routing_queue_utils.go
Ticket for this work: DEVTOOLING-1098
=> No JIRA: Fixed bug with media_settings_callback mode attr

genesyscloud/integration_credential/resource_genesyscloud_integration_credential.go
Fix the block label for the integration credential
=> DEVTOOLING-1135 Fix the block label for the integration credential

genesyscloud/tfexporter/genesyscloud_resource_exporter.go
Fixes DEVTOOLING-1137 by only outputting unresolveable attributes for non-data resource block types
=> Fixes DEVTOOLING-1137 by only outputting unresolveable attributes for non-data resource block types

genesyscloud/architect_ivr/resource_genesyscloud_architect_ivr.go
We need these retries to handle a race condition that occurs when migrating DNIS from one IVR to another.
We see the same error message as within PR 1641, but the root cause is different. 
https://github.com/MyPureCloud/terraform-provider-genesyscloud/pull/1641
Error:
Failed to create IVR config IVR_PROD error: error performing create inside function uploadArchitectIvrWithChunkingLogic: API Error: 400 - PhoneNumber with text '+33173290933' already exists.
PR 1641 allows the provider to properly remove the DNIS from the IVR. 
However, we bump into a race condition since these 2 operations happen at the same time:
1) Remove DNIS 1234 from IVR 1
2) Add DNIS 1234 to IVR 2 -- Create or Update IVR2
This PR retries on status code 400 for both update and create IVR operations to handle the race …
=> adding retries for create and update architect ivr

genesyscloud/resource_exporter/resource_name_sanitizer.go, genesyscloud/resource_exporter/resource_name_sanitizer_test.go, genesyscloud/tfexporter/genesyscloud_resource_exporter.go, genesyscloud/util/feature_toggles/exporter_sanitizer.go
Adds a new sanitizer that is dedicated to the needs of BCP. Also adds some extra context and comments, as well as tests for resource_name_sanitizer
See https://inindca.atlassian.net/browse/DEVTOOLING-1182 for details as to why this is required
=> Feature DEVTOOLING-1182 Adds a new sanitizer that is dedicated to the needs of BCP

genesyscloud/outbound_contact_list/resource_genesyscloud_outbound_contact_list_utils.go
Fixes DEVTOOLING-1191 by ensuring there is plenty of time to wait when retrieving the signed export URL for downloading a contact list.
=> Fixes DEVTOOLING-1191 - Large Contact Lists not always getting downloaded

genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
Fixes tests:
https://inindca.atlassian.net/browse/DEVTOOLING-1096
and
https://inindca.atlassian.net/browse/DEVTOOLING-1120
=> Fixes the TestAccResourceTfExportExcludeFilterResources.* tests

genesyscloud/architect_emergencygroup/resource_genesyscloud_architect_emergencygroup_test.go, genesyscloud/architect_flow/resource_genesyscloud_architect_flow_utils.go, genesyscloud/architect_flow/resource_genesyscloud_flow_test.go, genesyscloud/outbound_contact_list/resource_genesyscloud_outbound_contact_list.go
flow, outbound and some others that rely on those resources
=> [No-Jira] Fix flow and outbound acc tests

genesyscloud/architect_flow/resource_genesyscloud_architect_flow_utils.go, genesyscloud/architect_flow/resource_genesyscloud_flow_test.go
On Windows some characters are invalid for file names.
=> [Devtooling-1335] Ensure file path is valid with flow resolver

genesyscloud/outbound_ruleset/resource_genesyscloud_outbound_ruleset_schema.go, genesyscloud/outbound_ruleset/resource_genesyscloud_outbound_ruleset_test.go
Resolves https://github.com/MyPureCloud/terraform-provider-genesyscloud/issues/1891
Attribute was not in the `ValidateFunc`
Added it to a test to verify API handles it without failure
configuration in issue was able to be created after changes made
=> [No Jira] Added missing action_type_name
